/**
 * In-app changelog: the complete CHANGELOG.md history (v0.1.0 to current),
 * plain professional language, technical where it matters. Each card shows
 * one summary line; the chevron expands the full notes for that version.
 *
 * Kept newest-first and in step with CHANGELOG.md: release notes ship in two
 * places (the file and this screen) and a release that updates only one of
 * them reads as a missing version in the app.
 */

export interface ChangelogEntry {
  readonly version: string;
  readonly date: string;
  readonly summaryEn: string;
  readonly summaryMs: string;
  readonly full: string;
}

export const CHANGELOG_ENTRIES: readonly ChangelogEntry[] = [
  {
    version: "1.8.0",
    date: "2026-10-09",
    summaryEn:
      "Images, managed tools, subscriptions, post-processing, tool packs, remote access — one big stable release.",
    summaryMs:
      "Imej, alatan terurus, langganan, pasca-proses, pek alatan, akses jauh — satu keluaran besar yang stabil.",
    full: [
      "Added — images & engines",
      "- yt-dlp / gallery-dl router (Auto / Video / Images, per-link and per-batch override), engine badges, interrupted recovery, partial retry.",
      "- Gallery preview: image links probe into count + thumbnails + select, Download all or selected; Try-other-engine on failures; live file counters.",
      "- Images settings: folders, templates, sleeps, retries, proxy, archive, sidecar, raw config override + reset.",
      "",
      "Added — tools, queue, library",
      "- Tools & Engines: versions, Update / Reinstall / Rollback, yt-dlp channel, Update-all, Doctor with one-click fixes; outdated banner; stalled Restart; Smallest preset; custom -f selector.",
      "- Queue v2 (priorities, time window, per-download proxy), subscriptions (auto/notify, backoff + auto-disable), Library filters/sorts/views, corrupt-store recovery.",
      "",
      "Added — post-processing, packs, remote",
      "- Pipeline (convert, auto-tag, compress, CBZ/ugoira, transcription, rclone upload); Tool Packs (Streamlink, N_m3u8DL-RE, whisper, rclone); Remote access (loopback API, opt-in LAN, PWA, extension, CLI, Discord/Telegram pings).",
      "",
      "Trust",
      "- Unsigned build with SHA-256 checksums + SBOM; opt-in local crash reports; Report-a-bug; SECURITY.md and CI.",
    ].join("\n"),
  },
  {
    version: "1.7.2",
    date: "2026-10-05",
    summaryEn:
      "The window stays where you put it, Stats knows the real size, every yt-dlp format works, and the buttons work.",
    summaryMs:
      "Window kekal di tempat anda letak, Stats tahu saiz sebenar, semua format yt-dlp berfungsi, dan butang berfungsi.",
    full: [
      "Fixed — reported",
      "- The window jumped back to the middle of the screen: window chrome is re-applied on every theme change and every apply re-centred it. It now stays where you put it and reopens there.",
      "- Stats showed “Unknown” for total size: yt-dlp's post-processing lines carry no byte counts and overwrote the size already reported. Sizes are now monotonic and measured from the finished file, and existing history rows are back-filled.",
      "- Preview showed 0:00 and could not be scrubbed: the in-app media protocol now speaks HTTP byte ranges and streams the file.",
      "- Copy log / Copy diagnostics always failed: there was no main-side clipboard write, so the buttons relied on a DOM API the sandbox refuses.",
      "- Refresh and Show command were permanently disabled: they waited for a manually picked job. The newest job is preselected now.",
      "- Search boxes and the Batch buttons looked dead: Downloads had no search box on an empty queue, the toast column and the skip link silently swallowed clicks underneath them, and a payload without an extractor crashed the whole Home view.",
      "- Batch gave no feedback: a paste with no links, a throwing request-id helper and a failing analyze pool were all silent.",
      "",
      "Fixed — found by the audit",
      "- “Already downloaded” never worked: the archive lookup lowercased the whole identity key while video ids are case-sensitive.",
      "- A settings change could silently revert: a slow settings load landing after a save rolled the change back.",
      "- Backup restore could destroy history: it cleared first and appended afterwards, swallowing failures. It is one atomic replace now.",
      "- Restoring a large backup froze the app: every append re-read and rewrote the whole history file.",
      "- The update popup was a trap after a failure: no Close, no Escape, no backdrop click.",
      "- Update / repair buttons blamed the wrong thing when a download was merely paused.",
      "- Copy/Save diagnostics could do nothing at all on a corrupt history timestamp.",
      "- A crashed view told you nothing: the message is shown and logged now.",
      "- Notification permission was requested on every launch even when notifications were off.",
      "- The update-download host allowlist accepted evil-github.com.",
      "- The main thread no longer blocks while scanning the download folder or checking hundreds of paths, and the metadata dump is bounded.",
      "- Toast auto-dismiss timers are cancelled instead of firing after the toast is gone.",
      "- Context-menu arrow keys wrap correctly and Left returns to the item that opened the submenu.",
      "- A deep link or .fluxdl file arriving during launch is delivered instead of dropped.",
      "",
      "Changed",
      "- The e2e suite is repaired: 8 tests had been failing, and one of them accepted “Copy failed.” as a pass — which is why the clipboard bug survived. All 29 pass.",
      "- Every search box is a real search field with a clear button and a live match count.",
      "",
      "Added — full format support",
      "- Every container yt-dlp can produce is now recognised, so a finished MKV/AVI/FLV/MOV/3GP/TS/VOB/WMV/MKA/DTS file no longer shows as “Missing” and can be previewed, opened and measured.",
      "- Output container picker (Settings, plus per-job in Advanced and per-row in Batch): mp4, mkv, webm, avi, flv, mov, gif — exactly what the bundled yt-dlp accepts.",
      "- Audio formats cover yt-dlp's whole --audio-format set: MP3, M4A, AAC, Opus, Vorbis, FLAC, ALAC, WAV, plus Best which keeps the source stream untouched.",
      "- Polite pacing in Settings ▸ Network: request delay, min/max delay before each download, and a subtitle delay, mapping onto yt-dlp's documented sleep flags with Off / Light / Standard presets.",
      "",
      "Legal",
      "- README now states it explicitly: MIT licence with the full warranty disclaimer, neutral branding, no DRM circumvention, zero telemetry — plus the practical guidance for avoiding an IP rate limit.",
    ].join("\n"),
  },
  {
    version: "1.7.1",
    date: "2026-10-04",
    summaryEn: "The window is now fixed at 1180x820 — no resize, no maximize, centred.",
    summaryMs: "Window sekarang tetap 1180x820 — tak boleh resize, tak boleh maximize, di-center.",
    full: [
      "Fixed",
      "- The window could still be resized by dragging its edges, even with maximize disabled. Resizing is now off at the window level, which also makes F11 / Alt+Enter fullscreen a no-op, and the minimum and maximum sizes are pinned to the exact size as a second lock.",
      "- A window size left over from an older build could return on leaving mini mode. Nothing is remembered any more: each mode has exactly one size.",
      "- On small or high-DPI screens the fixed size shrinks to fit the work area instead of pushing the title bar or the last row off-screen.",
      "- Leaving mini mode no longer leaves the full window in the compact window's top-left corner; it re-centres on the current display.",
      "- Centring no longer clamps the position to zero, so a monitor to the left of the primary one no longer gets the window thrown onto the wrong display.",
      "",
      "Changed",
      "- Normal-mode size 1120x760 -> 1180x820: a little more room for the queue, settings and library.",
      "- The window opens centred on the primary display.",
      "- Mini mode (360x520) is fixed too, matching the main window.",
    ].join("\n"),
  },
  {
    version: "1.7.0",
    date: "2026-10-04",
    summaryEn: "Clean quit & stability: X really quits, bot checks explained, mini revamp.",
    summaryMs: "Quit bersih & kestabilan: X betul-betul quit, bot check jelas, mini dibaikkan.",
    full: [
      "Fixed",
      "- The X button could leave FluxDL (or orphaned yt-dlp/ffmpeg children) running in Task Manager. Quitting now tree-kills the whole child process tree and a force-exit timer bounds teardown at ~3.5 s.",
      "- Closing with active downloads silently killed them. X now asks: Quit anyway (.part files kept for resume) / Hide to tray / Cancel.",
      "- YouTube \"Sign in to confirm you're not a bot\" / PO Token failures were mislabelled as age-restriction. They now map to a dedicated bot-check error with cookie and engine-update actions.",
      "- Metadata probes could fail on a yt-dlp warning preamble mixed into stdout; the JSON payload is now sliced before parsing.",
      "- Log toolbar buttons sat glued to the search box; the filter/action row now has its own rhythm.",
      "- Leaving mini mode kept the window at the compact 360x520 size; the app now always boots into the normal window and the minimum size is lowered before shrinking.",
      "",
      "Added",
      "- Quit confirmation with the number of active downloads.",
      "- Mini mode button in the titlebar (beside the theme dots) — no more tray-hunting. Ctrl+Shift+M still works.",
      "- Mini view revamp: overall progress bar, per-row pause/resume/cancel, failed-jobs retry-all, speed/ETA/percent, scrolling list.",
    ].join("\n"),
  },
  {
    version: "1.6.1",
    date: "2026-10-04",
    summaryEn: "Update overhaul: launch popup, auto-install, plus UI fixes.",
    summaryMs: "Romakan kemas kini: popup launch, pasang-auto, dan baiki UI.",
    full: [
      "Fixed",
      "- The Logs update button could keep showing the old version for up to an hour (hourly cache). It now force-refreshes on every click.",
      "- Paste reported an invalid link on freshly-copied YouTube URLs: reads now go through the main process, with invisible characters and wrapping quotes stripped.",
      "- Tray icon could ghost after terminate; it is now destroyed on will-quit.",
      "- The Library icon pointed upside-down; books now stand on their shelves.",
      "- Side-by-side buttons had mismatched heights; both tiers now share fixed heights (40px standard, 30px small).",
      "- The X button left the process running (nothing called app.quit, so teardown never ran). Closing now drives a real quit on both .exe and portable.",
      "",
      "Added",
      "- Launch update popup: latest version, Setup/Portable sizes, release notes, publish date, Later / Skip-this-version / Download & install.",
      "- In-app download with progress, then automatic silent install on completion. A FluxDL-updated-to-<v>.txt note is left in the download folder on first boot.",
      "- Full in-app changelog with per-version read-more (this screen).",
      "- Themed scrollbars across every list, log and input.",
      "- Settings page regrouped into labelled sections with even row rhythm.",
      "- Jump list tasks, taskbar badge count, auto-start option, icon-only sidebar under 720px, .fluxdl batch files.",
    ].join("\n"),
  },
  {
    version: "1.6.0",
    date: "2026-10-04",
    summaryEn: "Frictionless & Trustworthy: redesigns plus Smart Queue and more.",
    summaryMs: "Lancar & Boleh Dipercayai: reka semula serta Baris Pintar.",
    full: [
      "Fixed",
      "- Native dialogs are now titled FluxDL instead of @grabber/desktop.",
      "- Onboarding buttons no longer sit flush against the folder input.",
      "- Subtitles include auto-generated captions by default; audio pins the best quality level.",
      "- Multi-link paste/drop goes to Batch instead of silently keeping the first link.",
      "",
      "Added",
      "- Single-instance lock, fluxdl:// links and CLI URLs, graceful shutdown.",
      "- Close-button choice (hide to tray or quit) and optional minimize-to-tray.",
      "- Downloads search with typo tolerance, status filters, quick throttle, queue ETA, bandwidth sparkline.",
      "- App + yt-dlp update reminders (launch check + Logs screen); in-app Library preview.",
      "- Ctrl+1 to Ctrl+7 view jumps, per-site smart presets, scheduled downloads, channel watchlist.",
      "- Undo for queue sweeps, backup and restore, storage insights with orphan cleaner.",
      "- Reworked README with banner, feature tour and architecture diagram.",
    ].join("\n"),
  },
  {
    version: "1.5.1",
    date: "2026-10-04",
    summaryEn: "Changelog tab, real quit by default, live onboarding themes.",
    summaryMs: "Tab Log Perubahan, quit sebenar lalai, tema onboarding live.",
    full: [
      "Fixed",
      "- The X button quits for real by default; hiding to tray is opt-in.",
      "- Onboarding theme picks preview live across the whole app.",
      "",
      "Added",
      "- In-app Changelog tab (Ctrl+7): the release history from v0.1.0 to the current version.",
    ].join("\n"),
  },
  {
    version: "1.5.0",
    date: "2026-10-04",
    summaryEn: "Stability core: single instance, auto-subs, top audio quality.",
    summaryMs: "Teras kestabilan: single instance, auto-subs, audio terbaik.",
    full: [
      "Fixed",
      "- Single-instance lock: a second launch focuses the running window and forwards its link instead of racing it.",
      "- Subtitles now include auto-generated captions (most videos have no manual subtitles).",
      "- Audio downloads pin the best quality level instead of the ~160kbps default.",
      "- Quitting keeps .part files so downloads resume on next boot.",
      "",
      "Added",
      "- fluxdl:// links and FluxDL.exe <url> deep-link support.",
      "- Quick speed throttle, Downloads search and filters, whole-queue ETA, live bandwidth sparkline.",
      "- Close/minimize-to-tray options and system-theme following.",
      "- In-app audio/video preview served over an allowlisted protocol.",
    ].join("\n"),
  },
  {
    version: "1.4.1",
    date: "2026-10-04",
    summaryEn: "Critical persistence and re-download fixes.",
    summaryMs: "Baiki kritikal simpanan dan muat-semula.",
    full: [
      "Fixed",
      "- Settings never saved in any released build (main is CommonJS, the store was ESM-only). Settings are now atomic JSON; existing files keep loading.",
      "- A failed save now shows an error instead of failing silently.",
      "- Library Download again confirms and really re-downloads (yt-dlp used to answer already-downloaded and exit 0).",
      "- Archive downloads no longer fail when the data folder does not exist yet.",
      "",
      "Added",
      "- Real-engine settings tests: every control verified to reach disk and survive reload and restart.",
    ].join("\n"),
  },
  {
    version: "1.4.0",
    date: "2026-10-04",
    summaryEn: "Live streams, chapters, audio tags, mini window, stats, light theme.",
    summaryMs: "Siaran langsung, bab, tag audio, mini, statistik, tema cerah.",
    full: [
      "Fixed",
      "- Live-stream and chapter flags were silently dropped between UI and binary; one allow-list and one projection now carry them.",
      "- Sidebar stayed visible in mini mode; fixed globally.",
      "- Idle app rewrote queue.json every second; writes are now gated on real changes (65 writes/65 s down to 0).",
      "",
      "Added",
      "- Audio metadata editor (title/artist/album/year) with injection-safe escaping, verified against the real binary.",
      "- Mini always-on-top window (Ctrl+Shift+M) with tray checkbox.",
      "- Stats screen derived from history: totals, 12-week chart, top uploaders, preset mix.",
      "- Fourth theme Paper (light) with darkened status colours.",
      "- Windows High Contrast support via a forced-colors pass.",
      "- Signing documentation and SmartScreen guidance (builds are unsigned).",
      "",
      "Known limitations",
      "- Builds are unsigned: SmartScreen shows Windows protected your PC. Use More info, Run anyway.",
      "- yt-dlp prints non-ASCII paths as mojibake; the recovery scan covers the common case.",
      "- Live integration tests need internet and can time out on slow networks.",
    ].join("\n"),
  },
  {
    version: "1.3.0",
    date: "2026-10-03",
    summaryEn: "Recovery, retries, settings search, log triage, polish.",
    summaryMs: "Pemulihan, cuba-semula, carian tetapan, triaj log.",
    full: [
      "Added",
      "- Destination recovery for non-ASCII folders (mojibake scan).",
      "- Retry countdown with bulk Retry-all.",
      "- Settings search with match counts and hidden rows.",
      "- Shortcut help dialog, log triage tools, filename template preview.",
      "- Window title counts, toast file actions, accessibility pass.",
      "",
      "Fixed",
      "- Extractor/videoId no longer dropped on the queue to engine handoff.",
      "- Settings ghost-input duplication fixed with stable keys.",
      "- E2E mock drift fixed with a pinned settings-shape test.",
    ].join("\n"),
  },
  {
    version: "1.2.0",
    date: "2026-10-03",
    summaryEn: "Palette, onboarding, Malay language, library health.",
    summaryMs: "Palet, onboarding, Bahasa Melayu, kesihatan pustaka.",
    full: [
      "Added",
      "- Command palette (Ctrl+K) with fuzzy search and recency boost.",
      "- First-run onboarding: folder, theme and default preset in 3 steps.",
      "- Faster cancellable analyze with LRU cache and skeleton shimmer.",
      "- Dynamic thumbnail accents, density toggle, accent colour picker.",
      "- Smarter playlists: downloaded badges, filters, per-entry presets, subfolders.",
      "- Full Bahasa Melayu + English dictionaries with key-parity typecheck.",
      "- Library health: missing-file badges with Locate, Remove and Re-download.",
      "",
      "Fixed",
      "- Resume after pause no longer sticks on paused forever.",
      "- Merged/extracted destinations and trust-boundary path checks.",
    ].join("\n"),
  },
  {
    version: "1.1.0",
    date: "2026-10-03",
    summaryEn: "Presets, batch, duplicates, errors, taskbar, diagnostics.",
    summaryMs: "Pratetap, kelompok, duplikat, ralat, taskbar, diagnostik.",
    full: [
      "Added",
      "- Compatible MP4 preset plus preferred-codec setting via format sort, with per-preset size estimates.",
      "- Batch panel: multi-line paste or .txt import, per-row status, presets and playlist expand.",
      "- Duplicate guard by extractor and id, with Skip / Download anyway / Open existing.",
      "- Download archive support with per-playlist opt-out and one-click clearing.",
      "- Actionable errors: retry, update-and-retry, cookie pickers, repair, settings deep links.",
      "- Taskbar progress, aggregate sidebar status and tray tooltip (4 updates/s max).",
      "- Card context menus and bulk queue controls with drag reorder.",
      "- One-click diagnostics report with secret redaction, copy and save.",
      "",
      "Fixed",
      "- Merged/extracted downloads report the final file, not deleted temps.",
      "- Renderer paths confined to download roots or known destinations.",
    ].join("\n"),
  },
  {
    version: "0.1.0",
    date: "2026-10-02",
    summaryEn: "Initial Windows release.",
    summaryMs: "Release Windows pertama.",
    full: [
      "Initial Windows release: Electron + React + TypeScript GUI for yt-dlp",
      "with queueing, themes, self-updating engine binaries, persisted",
      "settings/queue/history, tray behavior, and NSIS + portable builds.",
    ].join("\n"),
  },
];
