/**
 * In-app changelog: the complete CHANGELOG.md history (v0.1.0 to current),
 * plain professional language, technical where it matters. Each card shows
 * one summary line; the chevron expands the full notes for that version.
 */

export interface ChangelogEntry {
  readonly version: string;
  readonly date: string;
  readonly summaryEn: string;
  readonly summaryMs: string;
  readonly full: string;
}

export const CHANGELOG_ENTRIES: readonly ChangelogEntry[] = [
  {
    version: "1.6.1",
    date: "2026-10-04",
    summaryEn: "Update overhaul: launch popup, auto-install, plus UI fixes.",
    summaryMs: "Romakan kemas kini: popup launch, pasang-auto, dan baiki UI.",
    full: [
      "Fixed",
      "- The Logs update button could keep showing the old version for up to an hour (hourly cache). It now force-refreshes on every click.",
      "- Paste reported an invalid link on freshly-copied YouTube URLs: reads now go through the main process, with invisible characters and wrapping quotes stripped.",
      "- Tray icon could ghost after terminate; it is now destroyed on will-quit.",
      "- The Library icon pointed upside-down; books now stand on their shelves.",
      "- Side-by-side buttons had mismatched heights; both tiers now share fixed heights (40px standard, 30px small).",
      "- The X button left the process running (nothing called app.quit, so teardown never ran). Closing now drives a real quit on both .exe and portable.",
      "",
      "Added",
      "- Launch update popup: latest version, Setup/Portable sizes, release notes, publish date, Later / Skip-this-version / Download & install.",
      "- In-app download with progress, then automatic silent install on completion. A FluxDL-updated-to-<v>.txt note is left in the download folder on first boot.",
      "- Full in-app changelog with per-version read-more (this screen).",
      "- Themed scrollbars across every list, log and input.",
      "- Settings page regrouped into labelled sections with even row rhythm.",
      "- Jump list tasks, taskbar badge count, auto-start option, icon-only sidebar under 720px, .fluxdl batch files.",
    ].join("\n"),
  },
  {
    version: "1.6.0",
    date: "2026-10-04",
    summaryEn: "Frictionless & Trustworthy: redesigns plus Smart Queue and more.",
    summaryMs: "Lancar & Boleh Dipercayai: reka semula serta Baris Pintar.",
    full: [
      "Fixed",
      "- Native dialogs are now titled FluxDL instead of @grabber/desktop.",
      "- Onboarding buttons no longer sit flush against the folder input.",
      "- Subtitles include auto-generated captions by default; audio pins the best quality level.",
      "- Multi-link paste/drop goes to Batch instead of silently keeping the first link.",
      "",
      "Added",
      "- Single-instance lock, fluxdl:// links and CLI URLs, graceful shutdown.",
      "- Close-button choice (hide to tray or quit) and optional minimize-to-tray.",
      "- Downloads search with typo tolerance, status filters, quick throttle, queue ETA, bandwidth sparkline.",
      "- App + yt-dlp update reminders (launch check + Logs screen); in-app Library preview.",
      "- Ctrl+1 to Ctrl+7 view jumps, per-site smart presets, scheduled downloads, channel watchlist.",
      "- Undo for queue sweeps, backup and restore, storage insights with orphan cleaner.",
      "- Reworked README with banner, feature tour and architecture diagram.",
    ].join("\n"),
  },
  {
    version: "1.5.1",
    date: "2026-10-04",
    summaryEn: "Changelog tab, real quit by default, live onboarding themes.",
    summaryMs: "Tab Log Perubahan, quit sebenar lalai, tema onboarding live.",
    full: [
      "Fixed",
      "- The X button quits for real by default; hiding to tray is opt-in.",
      "- Onboarding theme picks preview live across the whole app.",
      "",
      "Added",
      "- In-app Changelog tab (Ctrl+7): the release history from v0.1.0 to the current version.",
    ].join("\n"),
  },
  {
    version: "1.5.0",
    date: "2026-10-04",
    summaryEn: "Stability core: single instance, auto-subs, top audio quality.",
    summaryMs: "Teras kestabilan: single instance, auto-subs, audio terbaik.",
    full: [
      "Fixed",
      "- Single-instance lock: a second launch focuses the running window and forwards its link instead of racing it.",
      "- Subtitles now include auto-generated captions (most videos have no manual subtitles).",
      "- Audio downloads pin the best quality level instead of the ~160kbps default.",
      "- Quitting keeps .part files so downloads resume on next boot.",
      "",
      "Added",
      "- fluxdl:// links and FluxDL.exe <url> deep-link support.",
      "- Quick speed throttle, Downloads search and filters, whole-queue ETA, live bandwidth sparkline.",
      "- Close/minimize-to-tray options and system-theme following.",
      "- In-app audio/video preview served over an allowlisted protocol.",
    ].join("\n"),
  },
  {
    version: "1.4.1",
    date: "2026-10-04",
    summaryEn: "Critical persistence and re-download fixes.",
    summaryMs: "Baiki kritikal simpanan dan muat-semula.",
    full: [
      "Fixed",
      "- Settings never saved in any released build (main is CommonJS, the store was ESM-only). Settings are now atomic JSON; existing files keep loading.",
      "- A failed save now shows an error instead of failing silently.",
      "- Library Download again confirms and really re-downloads (yt-dlp used to answer already-downloaded and exit 0).",
      "- Archive downloads no longer fail when the data folder does not exist yet.",
      "",
      "Added",
      "- Real-engine settings tests: every control verified to reach disk and survive reload and restart.",
    ].join("\n"),
  },
  {
    version: "1.4.0",
    date: "2026-10-04",
    summaryEn: "Live streams, chapters, audio tags, mini window, stats, light theme.",
    summaryMs: "Siaran langsung, bab, tag audio, mini, statistik, tema cerah.",
    full: [
      "Fixed",
      "- Live-stream and chapter flags were silently dropped between UI and binary; one allow-list and one projection now carry them.",
      "- Sidebar stayed visible in mini mode; fixed globally.",
      "- Idle app rewrote queue.json every second; writes are now gated on real changes (65 writes/65 s down to 0).",
      "",
      "Added",
      "- Audio metadata editor (title/artist/album/year) with injection-safe escaping, verified against the real binary.",
      "- Mini always-on-top window (Ctrl+Shift+M) with tray checkbox.",
      "- Stats screen derived from history: totals, 12-week chart, top uploaders, preset mix.",
      "- Fourth theme Paper (light) with darkened status colours.",
      "- Windows High Contrast support via a forced-colors pass.",
      "- Signing documentation and SmartScreen guidance (builds are unsigned).",
      "",
      "Known limitations",
      "- Builds are unsigned: SmartScreen shows Windows protected your PC. Use More info, Run anyway.",
      "- yt-dlp prints non-ASCII paths as mojibake; the recovery scan covers the common case.",
      "- Live integration tests need internet and can time out on slow networks.",
    ].join("\n"),
  },
  {
    version: "1.3.0",
    date: "2026-10-03",
    summaryEn: "Recovery, retries, settings search, log triage, polish.",
    summaryMs: "Pemulihan, cuba-semula, carian tetapan, triaj log.",
    full: [
      "Added",
      "- Destination recovery for non-ASCII folders (mojibake scan).",
      "- Retry countdown with bulk Retry-all.",
      "- Settings search with match counts and hidden rows.",
      "- Shortcut help dialog, log triage tools, filename template preview.",
      "- Window title counts, toast file actions, accessibility pass.",
      "",
      "Fixed",
      "- Extractor/videoId no longer dropped on the queue to engine handoff.",
      "- Settings ghost-input duplication fixed with stable keys.",
      "- E2E mock drift fixed with a pinned settings-shape test.",
    ].join("\n"),
  },
  {
    version: "1.2.0",
    date: "2026-10-03",
    summaryEn: "Palette, onboarding, Malay language, library health.",
    summaryMs: "Palet, onboarding, Bahasa Melayu, kesihatan pustaka.",
    full: [
      "Added",
      "- Command palette (Ctrl+K) with fuzzy search and recency boost.",
      "- First-run onboarding: folder, theme and default preset in 3 steps.",
      "- Faster cancellable analyze with LRU cache and skeleton shimmer.",
      "- Dynamic thumbnail accents, density toggle, accent colour picker.",
      "- Smarter playlists: downloaded badges, filters, per-entry presets, subfolders.",
      "- Full Bahasa Melayu + English dictionaries with key-parity typecheck.",
      "- Library health: missing-file badges with Locate, Remove and Re-download.",
      "",
      "Fixed",
      "- Resume after pause no longer sticks on paused forever.",
      "- Merged/extracted destinations and trust-boundary path checks.",
    ].join("\n"),
  },
  {
    version: "1.1.0",
    date: "2026-10-03",
    summaryEn: "Presets, batch, duplicates, errors, taskbar, diagnostics.",
    summaryMs: "Pratetap, kelompok, duplikat, ralat, taskbar, diagnostik.",
    full: [
      "Added",
      "- Compatible MP4 preset plus preferred-codec setting via format sort, with per-preset size estimates.",
      "- Batch panel: multi-line paste or .txt import, per-row status, presets and playlist expand.",
      "- Duplicate guard by extractor and id, with Skip / Download anyway / Open existing.",
      "- Download archive support with per-playlist opt-out and one-click clearing.",
      "- Actionable errors: retry, update-and-retry, cookie pickers, repair, settings deep links.",
      "- Taskbar progress, aggregate sidebar status and tray tooltip (4 updates/s max).",
      "- Card context menus and bulk queue controls with drag reorder.",
      "- One-click diagnostics report with secret redaction, copy and save.",
      "",
      "Fixed",
      "- Merged/extracted downloads report the final file, not deleted temps.",
      "- Renderer paths confined to download roots or known destinations.",
    ].join("\n"),
  },
  {
    version: "0.1.0",
    date: "2026-10-02",
    summaryEn: "Initial Windows release.",
    summaryMs: "Release Windows pertama.",
    full: [
      "Initial Windows release: Electron + React + TypeScript GUI for yt-dlp",
      "with queueing, themes, self-updating engine binaries, persisted",
      "settings/queue/history, tray behavior, and NSIS + portable builds.",
    ].join("\n"),
  },
];
