/**
 * All user-facing strings in one file. EN is the source of truth; MS is
 * typed for key parity (a missing key fails typecheck). Screens read the
 * active dictionary via useStrings() (locale.ts) so a language switch
 * re-renders. strings.ts itself stays dependency-free (main imports it).
 */
const EN = {
  appUnavailable: "This UI must run inside the desktop shell.",
  appUnavailableTitle: "Unavailable",
  navThemeGroup: "Theme",
  skipToContent: "Skip to content",
  toast: {
    region: "Notifications",
    dismiss: "Dismiss",
    finished: "Finished",
    failed: "Failed",
    removed: "Removed from history.",
    cleared: "History cleared.",
    queued: "Queued for download.",
    finishedSummary: "{done} finished · {failed} failed.",
  },
  status: {
    activeCount: "{count} active",
    ready: "Ready",
    working: "Working…",
    pausedResume: "{count} paused from last time — resume them?",
    offline: "Offline — downloads resume when reconnected.",
    recoverySettings: "Settings were corrupt, so they were reset.",
    recoveryQueue: "The download queue was corrupt, so it was cleared.",
    recoveryWatchlist: "The watchlist was corrupt, so it was cleared.",
    recoveryKept: "The old file was kept as {backup}.",
  },
  engine: {
    video: "Video",
    images: "Images",
    auto: "Auto",
    videoOnly: "Video (yt-dlp)",
    imagesOnly: "Images (gallery-dl)",
    tryOther: "Try other engine",
    downloadBoth: "Download both",
    unsupported: "This link is not supported by either engine.",
    interrupted: "Interrupted — resume to retry",
    partial: "Partial",
    probing: "Probing…",
    galleryNeedsBinary: "gallery-dl is not installed yet. Run the Tools check to install it.",
    packNeedsBinary: "This engine is an optional pack and is not installed yet. Open Settings → Tool Packs to install it.",
  },
  mini: {
    title: "Mini mode",
    exit: "Exit mini",
    empty: "Nothing running.",
  },
  home: {
    title: "Home",
    urlLabel: "Video URL",
    urlPlaceholder: "Paste a link…",
    paste: "Paste",
    analyze: "Analyze",
    quickDownload: "Quick download",
    analyzing: "Analyzing…",
    cancelAnalyze: "Cancel",
    reanalyze: "Re-analyze",
    watchClipboard: "Watch clipboard",
    dropHint: "Tip: you can also drag-drop a link here.",
    shortcutsHint: "Shortcuts: Ctrl+V pastes and analyzes · Ctrl+K commands · Ctrl+, opens Settings · ? lists shortcuts.",
    invalidUrl: "That link does not look valid.",
    analyzeFailed: "Could not analyze this link. See Logs for details.",
    previewDuration: "Duration",
    unknownDuration: "—",
    kindVideo: "Video",
    kindAudio: "Audio",
    advancedFormats: "Advanced formats",
    useFormat: "Use",
    presetCompatible: "Compatible MP4",
    sizeUnknown: "-",
    entriesSelected: "selected",
    selectAll: "All",
    selectNone: "None",
    queueSelected: "Download selected",
    queueSingle: "Download",
    queuedToast: "Queued {count}.",
    multiToBatch: "Detected {count} links — added to Batch below.",
    inputMode: "Link input mode",
    modeSingle: "Single link",
    modeBatch: "Batch",
    downloadRemaining: "Download remaining ({n})",
    upgradeHint: "Already in your Library ({preset}) — queue again to upgrade quality.",
    lowDiskConfirm: "Only {free} free on this drive — queue anyway?",
    playlistPresetNote: "The preset above applies to every selected entry.",
    liveBadge: "LIVE",
    upcomingBadge: "UPCOMING",
    streamlinkHint: "Live stream — Streamlink captures these more reliably.",
    streamlinkCapture: "Capture with Streamlink",
    streamlinkDismiss: "Dismiss",
    wasLiveBadge: "WAS LIVE",
    liveFromStart: "Record from start",
    waitForVideo: "Wait for stream to start",
    splitChapters: "Split by chapters",
    metadata: "Metadata",
    metaTitle: "Title",
    metaArtist: "Artist",
    metaAlbum: "Album",
    metaYear: "Year",
    metadataHint: "Written into the file tags. Leave a field empty to skip it.",
    perJobProxy: "Proxy (this download)",
    perJobProxyHint: "Empty = use the global proxy setting.",
    chaptersCount: "{count} chapters",
    chaptersList: "Chapters ({count})",
    engineOverride: "Engine",
    galleryTitle: "Image gallery",
    galleryCount: "{count} images",
    galleryDownloadAll: "Download all",
    galleryDownloadSelected: "Download selected",
    galleryProbing: "Probing gallery…",
    galleryCheck: "Check image gallery",
    galleryEmpty: "No images found here.",
    trimStart: "Trim start",
    trimEnd: "Trim end",
    trimHint: "Start–end section (seconds or MM:SS). Empty = whole video.",
    reverseEntries: "Reverse",
    presetSummary: "Preset: {preset}",
  },
  batch: {
    title: "Batch",
    description: "Paste many links at once, or drop a .txt file. One link per line.",
    inputLabel: "Links (one per line)",
    inputPlaceholder: "https://…\nhttps://…",
    add: "Add",
    chooseFile: "Choose .txt…",
    pasteClipboard: "Paste clipboard",
    analyzeAll: "Analyze all",
    analyzing: "Analyzing…",
    stop: "Stop",
    queueAllReady: "Queue all ready",
    queueing: "Queueing…",
    retryFailed: "Retry failed",
    remove: "Remove",
    expand: "Expand",
    clear: "Clear",
    useGlobalPreset: "Use global preset",
    useGlobalContainer: "Default container",
    presetLabel: "Preset",
    empty: "Nothing here yet. Paste links or choose a .txt file.",
    nothingFound: "No links found in that text — one full link per line.",
    needLinks: "Add some links first, then analyze them.",
    needReady: "Analyze the links first, then queue them.",
    analyzedAll: "Every link has been analyzed.",
    readyToQueue: "{n} analyzed and ready — queue them now.",
    invalidSkipped: "Invalid lines skipped: {n}",
    duplicatesSkipped: "Duplicates skipped: {n}",
    truncatedNote: "Stopped at 500 lines; the rest was ignored.",
    fileTooBig: "That file is over 1 MB.",
    statusPending: "Pending",
    statusAnalyzing: "Analyzing…",
    statusReady: "Ready",
    statusFailed: "Failed",
    queuedToast: "Queued {count}.",
  },
  playlist: {
    downloaded: "Downloaded",
    archived: "Archived",
    hideDownloaded: "Hide downloaded",
    filterPlaceholder: "Filter entries…",
    checking: "Checking downloaded…",
  },
  duplicate: {
    title: "Already downloaded?",
    queueMessage: "This link is already in your queue.",
    historyMessage: "You downloaded this before.",
    downloadedOn: "Downloaded:",
    skip: "Skip",
    downloadAnyway: "Download anyway",
    openFile: "Open existing file",
  },
  downloads: {
    title: "Downloads",
    empty: "Nothing here yet. Queue something from Home.",
    goHome: "Go to Home",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    retry: "Retry",
    retryAll: "Retry all failed",
    retryIn: "Retrying in {n}s · attempt {a}",
    attempt: "Attempt {a}",
    openFile: "Open file",
    showInFolder: "Show in folder",
    showFolder: "Open folder",
    pauseAll: "Pause all",
    resumeAll: "Resume all",
    cancelQueued: "Cancel queued",
    cancelledNote: "Cancelled {count} queued.",
    clearedNote: "Cleared {count}.",
    undo: "Undo",
    clearFinished: "Clear finished",
    bulkActions: "Bulk queue actions",
    recording: "Recording",
    stopRecording: "Stop recording",
    searchPlaceholder: "Search downloads…",
    filterAll: "All",
    filterActive: "Active",
    filterError: "Failed",
    filterDone: "Done",
    noMatch: "No downloads match.",
    clearFilters: "Clear search & filters",
    saveSearch: "Save search",
    savedSearches: "Saved",
    recentSearches: "Recent",
    removeSaved: "Remove",
    pin: "Pin",
    unpin: "Unpin",
    pinned: "Pinned",
    priorityHigh: "High priority",
    priorityNormal: "Normal priority",
    priorityLow: "Low priority",
    priorityCycle: "Priority: {label}",
    selectedCount: "{n} selected",
    clearSelection: "Clear selection",
    bulkPause: "Pause selected",
    bulkResume: "Resume selected",
    bulkRetry: "Retry selected",
    bulkCancel: "Cancel selected",
    copyLinks: "Copy links",
    linksCopied: "Links copied.",
    throttleLabel: "Speed",
    throttleUnlimited: "Unlimited",
    throttleNote: "Applies to new downloads.",
    queueEta: "Queue ETA {eta} · {size} left",
    schedule: "Schedule…",
    applySchedule: "Set",
    startsAt: "Starts {when}",
    clearSchedule: "Clear",
    reprocess: "Re-run post-processing",
    postRunning: "Post-processing is already running for these files.",
    postDone: "Post-processing finished.",
    postSaved: "Saved {size}.",
    postFailed: "Post-processing failed.",
    postNothing: "Nothing to process.",
    postTagLow: "Best match “{title}” scores {score} — apply it?",
    postTagApply: "Apply anyway",
    postMenuConvert: "Convert images",
    postMenuTag: "Tag audio files",
    postMenuCompress: "Compress video",
    postMenuTranscribe: "Transcribe audio (.srt)",
    postMenuUpload: "Upload via rclone",
    postMenuReprocess: "Re-run post-processing",
    postMenuMediaInfo: "Media info",
    galleryFiles: "{count} files",
    gallerySkipped: "{count} skipped",
    galleryFailed: "{count} failed",
    rerunGallery: "Re-run (skips finished)",
    stalled: "Stalled — no output for a while",
    restart: "Restart",
    outdatedBanner: "Some downloads failed: the engine looks outdated.",
    outdatedUpdate: "Update & retry all",
  },
  stats: {
    title: "Stats",
    empty: "No downloads recorded yet.",
    completed: "Completed",
    failed: "Failed",
    totalSize: "Total size",
    totalDuration: "Total duration",
    perWeek: "Per week",
    topUploaders: "Top uploaders",
    presetMix: "Presets",
    topSites: "Top sites",
    presetSuccess: "Success by preset",
    storage: "Storage",
    cleanOrphans: "Clean partials",
    storageCleaned: "Partial files cleaned.",
    presetAdvice: "A preset keeps failing — Compatible MP4 works almost everywhere.",
    unknown: "unknown",
    noUploaders: "No uploader data yet.",
    noData: "No data yet.",
    unknownNote: "{count} older entries have no size recorded.",
    derivedFromHistory:
      "Everything here is derived from download history. Clearing history clears these numbers.",
  },
  library: {
    title: "Library",
    searchPlaceholder: "Search title or link…",
    filterKind: "Type",
    filterKindAll: "All types",
    filterKindVideo: "Video",
    filterKindAudio: "Audio",
    filterEngine: "Engine",
    filterEngineAll: "All engines",
    filterSite: "Site (e.g. youtube)",
    sortLabel: "Sort",
    sortNewest: "Newest",
    sortOldest: "Oldest",
    sortTitle: "Title",
    sortSize: "Size",
    viewList: "List view",
    viewGrid: "Grid view",
    gridCapped: "Showing first {n} of {t} — refine search or filters to see more.",
    loading: "Loading…",
    empty: "No finished downloads yet.",
    emptySearch: "No matches.",
    results: "{n} of {t} shown",
    redownload: "Download again",
    remove: "Remove",
    clearAll: "Clear all",
    clearConfirm: "Remove all history entries?",
    redownloadConfirm: "Download “{title}” again? The existing file will be replaced.",
    missing: "Missing",
    locate: "Locate…",
    checking: "Checking files…",
    preview: "Preview",
    previewLoading: "Loading preview…",
    previewUnavailable: "Preview is not available for this file.",
    watchTitle: "Watchlist",
    watchAdd: "Add channel",
    watchPlaceholder: "Channel or playlist URL…",
    watchCheck: "Check",
    watchQueueNew: "Queue new ({n})",
    watchRemove: "Remove",
    watchEmpty: "No watched channels yet.",
    watchFirstCheck: "Baseline set — new uploads will appear here.",
    watchNew: "{n} new",
    watchLastChecked: "Last check: {when}",
    watchModeAuto: "Auto-download",
    watchModeNotify: "Notify only",
    watchPaused: "Paused",
    watchPause: "Pause",
    watchResume: "Resume",
    watchInterval: "Every {n} min",
    watchFolder: "Folder…",
    watchAutoDisabled: "Stopped after repeated failures — resume to retry.",
    watchCapConfirm: "{n} new items in “{title}” — queue them all?",
    watchAutoQueued: "Queued {n} new from “{title}”.",
    watchNotifyNew: "{n} new in “{title}”.",
    previewPip: "Picture-in-picture",
    previewFullscreen: "Fullscreen",
    mediaDetails: "Media details",
    mediaFormat: "Container",
    mediaDuration: "Duration",
    mediaSize: "Size",
    mediaVideo: "Video",
    mediaAudio: "Audio",
    mediaNoInfo: "No media info available.",
  },
  settings: {
    title: "Settings",
    loading: "Loading…",
    downloadDir: "Download folder",
    browse: "Browse…",
    filenameTemplate: "Filename template",
    filenamePresets: "Presets",
    templatePreview: "Preview: {name}",
    templateInvalid: "Template must include %(ext)s.",
    speedInvalid: "Use a rate like 4.2M, or leave empty for unlimited.",
    concurrency: "Simultaneous downloads (1–5)",
    analyzeTimeout: "Analyze timeout (seconds, 10–300)",
    speedLimit: "Speed limit (e.g. 4.2M, empty = unlimited)",
    proxy: "Proxy (empty = direct)",
    concurrencyGallery: "Simultaneous image downloads (1–5)",
    downloadWindowStart: "Download window start (HH:MM, empty = always)",
    downloadWindowEnd: "Download window end (HH:MM, empty = always)",
    windowInvalid: "Use 24-hour HH:MM, or leave empty.",
    cookies: "Cookies from browser (e.g. chrome, empty = off)",
    cookiesFile: "Cookies file (.txt, empty = off)",
    embedThumbnail: "Embed thumbnail",
    embedMetadata: "Embed metadata",
    subtitles: "Download subtitles",
    subtitleLangs: "Subtitle languages",
    embedSubs: "Embed subtitles",
    includeAutoSubs: "Include auto-generated subtitles",
    mergeContainer: "Output container",
    mergeContainerHint:
      "Applies to video downloads. Every container here is one the bundled yt-dlp can produce or remux into.",
    postTitle: "After download",
    ppConvert: "Convert images (JPG/PNG)",
    ppFormat: "Image format",
    ppQuality: "Image quality (1–100)",
    ppMaxDim: "Max image side (px)",
    ppStripExif: "Strip EXIF/GPS metadata",
    ppPackage: "Package galleries",
    ppPackageOff: "Off",
    ppUgoira: "Pixiv animation conversion",
    ppUgoiraOff: "Off",
    ppAutoTag: "Auto-tag audio (MusicBrainz)",
    ppAutoTagHint: "High-confidence matches only; needs internet.",
    ppCompress: "Compress video after download",
    ppCompressOff: "Off",
    ppCompressSmall: "Small",
    ppCompressBalanced: "Balanced",
    ppCompressArchive: "Archive",
    ppTranscribe: "Transcribe audio to subtitles (.srt, whisper, CPU)",
    ppTranscribeHint: "Needs the whisper pack + a model below (experimental).",
    ppWhisperModel: "Whisper model",
    ppRcloneRemote: "rclone remote folder (e.g. myremote:backups/)",
    ppRcloneRemoteHint: "rclone owns its config — FluxDL only stores this path, never credentials.",
    ppAutoUpload: "Auto-upload finished files via rclone",
    ppKeepOriginals: "Keep original files",
    ppKeepOriginalsHint: "Off moves originals to the Recycle Bin.",
    packsTitle: "Tool Packs",
    packNotInstalled: "Not installed",
    packInstalled: "Installed {v}",
    packInstall: "Install",
    packUpdate: "Update to {v}",
    packUpdateAll: "Update all",
    packCheckUpdates: "Check for updates",
    packRemove: "Remove",
    packUpToDate: "Up to date",
    packSize: "Download ≈ {size}",
    packDiskUsed: "On disk: {size}",
    packLicense: "License: {license}",
    packVerified: "SHA256SUMS-verified",
    packConsent: "I understand this project publishes no checksums file",
    packModels: "Speech models",
    packModelInstall: "Download",
    packModelRemove: "Remove",
    packWorking: "Working…",
    packCancel: "Cancel",
    packDone: "Done.",
    packFailed: "Pack operation failed.",
    pacingTitle: "Polite pacing",
    pacingRequests: "Delay between page requests (s)",
    pacingMin: "Minimum delay before each download (s)",
    pacingMax: "Maximum delay before each download (s)",
    pacingSubs: "Delay before each subtitle download (s)",
    pacingHint:
      "Empty = off. Raising these makes downloads look like ordinary viewing instead of a scrape, which reduces the chance of a platform rate-limiting your IP (HTTP 429). Slower, but safer.",
    pacingOff: "Off",
    pacingLight: "Light",
    pacingStandard: "Standard",
    containerLabel: "Container",
    containerDefault: "Default (from Settings)",
    codecPreference: "Preferred video codec",
    codecAuto: "Auto (site default)",
    codecH264: "H.264 (plays everywhere)",
    codecVp9: "VP9",
    codecAv1: "AV1 (smaller files)",
    thumbnailAccent: "Tint preview with thumbnail colour",
    skipArchived: "Skip playlist videos already in the archive",
    playlistSubfolder: "Download playlists into subfolders",
    clearArchive: "Clear archive…",
    backup: "Backup & restore",
    exportBackup: "Export backup…",
    importBackup: "Import backup…",
    backupDone: "Backup restored ({q} queued, {h} history, {w} watched, {d} dropped).",
    backupFailed: "Could not read that backup file.",
    archiveCleared: "Archive cleared.",
    archiveConfirm: "Forget every archived video? Playlists will download them again.",
    sponsorBlock: "Remove SponsorBlock segments",
    theme: "Theme",
    themes: {
      obsidian: "Obsidian",
      midnight: "Midnight",
      ember: "Ember",
      paper: "Paper",
    },
    density: "Density",
    densityComfortable: "Comfortable",
    densityCompact: "Compact",
    accent: "Accent colour",
    accentCustom: "Custom hex (#rrggbb)",
    accentReset: "Reset to theme default",
    accentWarning: "Low contrast on accent text — adjusted automatically.",
    postAction: "After download",
    postNone: "Do nothing",
    postOpen: "Open file",
    postReveal: "Show in folder",
    language: "Language",
    languageAuto: "Auto (system)",
    languageEnglish: "English",
    languageMalay: "Bahasa Melayu",
    historyLimit: "Keep history entries (10–5000)",
    autoCheckUpdate: "Check engine updates on launch",
    notifyFinished: "System notifications for finished downloads",
    crashReports: "Keep local crash reports (opt-in, never uploaded)",
    profiles: "One-click profiles",
    experimental: "Experimental features (may change or break)",
    sectionDownloads: "Downloads",
    sectionQuality: "Quality",
    sectionSubtitles: "Subtitles",
    sectionNetwork: "Network",
    sectionAppearance: "Appearance",
    sectionBehavior: "After download & window",
    sectionPresets: "Presets",
    sectionData: "Data & backup",
    followSystemTheme: "Follow the system light/dark mode",
    launchAtLogin: "Start with Windows (minimized to tray)",
    autoSort: "Sort into Music / Videos folders",
    profilesHint: "Applies a settings bundle instantly.",
    profileMusic: "Music",
    profileVideo: "Video",
    profileArchive: "Audio archive",
    closeBehavior: "Close button (X) action",
    closeTray: "Hide to tray (downloads continue)",
    closeQuit: "Quit the app",
    minimizeToTray: "Minimize button also hides to tray",
    saved: "Saved.",
    saveFailed: "Could not save: {detail}",
    search: "Search settings…",
    clearSearch: "Clear search",
    noMatch: "No settings match.",
    matchCount: "{n} of {t} settings",
    routerMode: "Download engine",
    autoUpdateTools: "Auto-update tools when idle",
    downloadRetries: "Network retries (empty = tool default)",
    concurrentFragments: "Concurrent fragments (empty = tool default)",
    socketTimeoutSec: "Socket timeout, seconds (empty = tool default)",
    useAria2c: "Use aria2c downloader when present",
    sponsorCats: "SponsorBlock categories",
    sponsorCatsHint: "Comma list, e.g. all,-filler. Applies when removal is on.",
    customFormat: "Custom format selector (-f, empty = off)",
    customFormatHint: "Advanced yt-dlp -f value. A per-link format still wins.",
    toolsTitle: "Tools & Engines",
    toolsUpdate: "Update",
    toolsReinstall: "Reinstall",
    toolsRollback: "Rollback",
    toolsUpdateAll: "Update all",
    toolsRunDoctor: "Run health check",
    toolsChannel: "yt-dlp channel",
    toolsLastChecked: "Last checked {when}",
    toolsNeverChecked: "Never checked",
    toolsMissing: "Missing",
    toolsUpdated: "Tools updated.",
    toolsDoctorOk: "All checks pass.",
    toolsInstallGuide: "Place {exe} in the app bin folder or on PATH.",
    toolsOpenSettings: "See {section} in Settings.",
    sectionImages: "Images (gallery-dl)",
    imagesDownloadDir: "Images folder (empty = Downloads/Images)",
    imagesFolderTemplate: "Gallery folder template",
    imagesFilenameTemplate: "Image filename template",
    imagesArchive: "Skip images already downloaded (archive)",
    imagesSidecar: "Save metadata sidecar (.json)",
    imagesCustom: "Raw config override (JSON, empty = generated)",
    imagesCustomHint: "Replaces the generated gallery-dl config. Reset restores the generated one.",
    imagesCustomReset: "Reset to generated",
    imagesCustomInvalid: "Not saved: {detail}",
    remoteTitle: "Remote access",
    remoteHint:
      "Control FluxDL from this computer's browser or extension. Loopback only — requests never leave this PC.",
    remoteEnable: "Enable local API server (127.0.0.1)",
    remotePort: "Port",
    remoteRunning: "Running on 127.0.0.1:{port}.",
    remoteStopped: "Stopped.",
    remoteErrEncryption: "Token store unavailable (OS encryption off) — the server cannot start.",
    remoteErrBind: "Could not bind the port — is another copy already running?",
    remoteErrUnknown: "Server error: {detail}",
    remoteCopyLink: "Copy pairing link",
    remoteCopied: "Pairing link copied.",
    remoteCopyFailed: "Could not copy the link.",
    remoteRotate: "Rotate token",
    remoteRotateConfirm:
      "Issue a new token? Paired browsers and extensions stop working until you pair again.",
    remoteRotated: "New token issued. Pair your devices again.",
    remoteRefresh: "Refresh status",
    remoteLanNote: "LAN is opt-in — read the warning first.",
    notifyTitle: "Notifications",
    notifyDiscord: "Discord webhook on finish/fail",
    notifyWebhook: "Webhook URL (stored encrypted)",
    notifyTelegram: "Telegram message on finish/fail",
    notifyChatId: "Chat ID",
    notifyToken: "Bot token (stored encrypted)",
    notifyTest: "Send test",
    notifyClear: "Clear",
    notifySent: "Test sent.",
    notifyFailed: "Notification failed.",
    lanEnable: "Allow LAN access",
    lanWarn: "Any device on your network with the token can queue and cancel downloads. Use an allowlist and auto-disable.",
    lanConfirm: "Expose the API to your local network? Anyone with the token can add and cancel downloads.",
    lanAllowlist: "IP allowlist (comma prefixes, empty = all LAN)",
    lanAutoDisable: "Auto-disable after hours (empty = stay on)",
    lanOn: "LAN open — token rotated. Pair again.",
    remoteAudit: "Download audit log",
  },
  logs: {
    title: "Logs & About",
    engineVersions: "Engine versions",
    appVersion: "App",
    ytdlpVersion: "yt-dlp",
    ffmpegVersion: "ffmpeg",
    checkUpdate: "Check for update",
    updating: "Updating…",
    upToDate: "Engine is up to date.",
    checkUpdates: "Check for updates",
    checkingUpdates: "Checking…",
    appUpToDate: "FluxDL is up to date ({v}).",
    appUpdateReady: "FluxDL {v} is available (you have {cur}).",
    appReleased: "Released {date}.",
    ytdlpUpToDate: "yt-dlp is up to date ({v}).",
    ytdlpUpdateReady: "yt-dlp {v} is available — use “Check for update” to install it.",
    updateCheckFailed: "Could not reach the update server (offline?).",
    getUpdate: "Get update",
    updateFailed: "Update failed. See below.",
    repairEngine: "Repair engine",
    repairing: "Repairing…",
    repaired: "Engine verified.",
    repairFailed: "Repair failed. The app may need reinstalling.",
    viewLog: "View",
    logPlaceholder: "Pick a job to inspect its raw engine log.",
    reportBug: "Report a bug",
    crashTitle: "Crash reports",
    crashClear: "Clear",
    crashEmpty: "No crash reports recorded.",
    noticesTitle: "Third-party notices",
    search: "Search log…",
    clearSearch: "Clear search",
    errorsOnly: "Errors only",
    follow: "Follow live log",
    refresh: "Refresh",
    copyLog: "Copy log",
    logCopied: "Log copied.",
    showCommand: "Show command",
    selectJobFirst: "Pick a job above to see its command line.",
    matchCount: "{n} matching lines",
    noMatch: "No matching lines.",
    copyrightNote:
      "You are responsible for respecting copyright and each site's terms. Only download content you own or are allowed to keep.",
  },
  safety: {
    exeMessage: "This file can run programs on your PC. Open “{name}” anyway?",
    exeOpen: "Open",
    exeCancel: "Cancel",
  },
  closeConfirm: {
    title: "Downloads still running?",
    message: "{count} download(s) still active. Quitting keeps partial files for resume.",
    quit: "Quit anyway",
    hide: "Hide to tray",
    cancel: "Cancel",
  },
  tasks: {
    newDownload: "New download",
    newDownloadDesc: "Open FluxDL to add a download",
    openFolder: "Open downloads folder",
    openFolderDesc: "Show the download folder",
  },
  errors: {
    viewCrashed: "This view crashed.",
    viewCrashedHint: "Your downloads keep running — only this screen needs a reload.",
    reloadView: "Reload view",
    actionRetry: "Retry",
    actionTryNm3u8dl: "Try with N_m3u8DL-RE",
    actionFailed: "That action failed. See Logs for details.",
    actionUpdateRetry: "Update engine & retry",
    actionCookiesOnce: "Use once",
    actionCookiesAlways: "Always use",
    actionRepair: "Repair engine",
    actionSettings: "Open settings",
    actionLogs: "Open logs",
    actionFolder: "Choose folder",
    cookiesLabel: "Read cookies from",
    updateBlockedBusy: "Pause or finish the active downloads first, then update.",
    engineUpdated: "Engine updated. Retrying…",
    engineRepairing: "Repairing…",
    engineRepaired: "Engine repaired and verified.",
    engineRepairFailed: "Repair failed. See Logs for details.",
  },
  browsers: {
    chrome: "Google Chrome",
    edge: "Microsoft Edge",
    firefox: "Firefox",
    brave: "Brave",
    chromium: "Chromium",
    opera: "Opera",
    vivaldi: "Vivaldi",
    whale: "Whale",
  },
  menu: {
    label: "Download actions",
    copyUrl: "Copy URL",
    copyPath: "Copy file path",
    retryPreset: "Retry with another preset…",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove from list",
    deleteFile: "Delete file",
    deleteFolder: "Delete folder",
    deleteConfirm: "Move this file to the Recycle Bin? The history entry is kept.",
    deleteFolderConfirm: "Move this folder to the Recycle Bin? The history entry is kept.",
    deletedToast: "Moved to the Recycle Bin.",
    fileDeleted: "File deleted",
    folderDeleted: "Folder deleted",
    copyFailed: "Copy failed.",
  },
  diagnostics: {
    copy: "Copy diagnostics",
    save: "Save .txt",
    includeUrls: "Include URLs (they may contain private links)",
    preview: "Report preview",
    copied: "Diagnostics copied.",
    saved: "Diagnostics saved.",
    reportTitle: "FluxDL diagnostics",
    reportVersions: "Versions",
    reportSettings: "Settings (redacted)",
    reportErrors: "Recent errors",
    reportNoErrors: "(none)",
    reportLog: "Log tail",
    reportNoLog: "(no log selected)",
    reportCrashes: "Crash reports (opt-in, local-only)",
  },
  commands: {
    title: "Command palette",
    placeholder: "Type a command…",
    empty: "No matching commands.",
    smartAction: "Smart action",
    pasteAnalyze: "Paste clipboard URL and analyze",
    goHome: "Go to Home",
    goDownloads: "Go to Downloads",
    goLibrary: "Go to Library",
    goStats: "Go to Stats",
    goSettings: "Go to Settings",
    goLogs: "Go to Logs",
    goChangelog: "Go to Changelog",
    themeObsidian: "Switch to Obsidian theme",
    themeMidnight: "Switch to Midnight theme",
    themePaper: "Use the Paper (light) theme",
    themeEmber: "Switch to Ember theme",
    updateEngine: "Update yt-dlp engine",
    openDownloadsFolder: "Open downloads folder",
    pauseAll: "Pause all downloads",
    resumeAll: "Resume all downloads",
    retryAll: "Retry all failed downloads",
    showShortcuts: "Show keyboard shortcuts",
    clearFinished: "Clear finished downloads",
    toggleDensity: "Toggle comfortable/compact density",
    toggleMiniMode: "Toggle mini mode (always on top)",
    settingsFolder: "Open Settings: download folder",
    settingsCookies: "Open Settings: cookies",
    settingsProxy: "Open Settings: proxy",
  },
  shortcuts: {
    title: "Keyboard shortcuts",
    close: "Close",
    paste: "Paste clipboard link and analyze",
    palette: "Open command palette",
    settings: "Open Settings",
    miniMode: "Toggle mini mode",
    navigate: "Jump between views (Ctrl+1…7)",
    help: "Open this shortcut list",
    dismiss: "Close dialogs",
  },
  changelog: {
    title: "Changelog",
    readMore: "Read more",
    showLess: "Show less",
  },
  updateModal: {
    title: "Update available",
    version: "FluxDL {v} is available",
    installed: "Installed: {cur}",
    published: "Published {date}",
    setupSize: "Setup installer · {size} (installs automatically)",
    portableSize: "Portable · {size} (manual)",
    notes: "What's new",
    noNotes: "See the Changelog tab after updating.",
    download: "Download & install",
    later: "Later",
    skip: "Skip this version",
    downloading: "Downloading… {received} of {total}",
    downloadingUnknown: "Downloading… {received}",
    installing: "Download complete — installing the new version…",
    failed: "Download failed: {detail}",
    retry: "Retry",
    ytdlpNote: "yt-dlp has an update too — see Logs.",
  },
  onboarding: {
    title: "Welcome to FluxDL",
    subtitle: "Three quick steps — you can change everything later in Settings.",
    stepFolder: "Where should downloads go?",
    browse: "Browse…",
    stepTheme: "Pick a theme",
    stepPreset: "Default preset",
    engineOk: "Engine ready",
    engineFail: "Engine check failed — you can still use the app.",
    back: "Back",
    next: "Next",
    done: "Done",
    skip: "Skip",
    replay: "Replay onboarding",
  },
} as const;

export type Strings = typeof EN;

/** Recursive key parity: a missing Bahasa Melayu key fails typecheck. */
export type Parity<T> = { [K in keyof T]: T[K] extends string ? string : Parity<T[K]> };

const MS: Parity<Strings> = {
  appUnavailable: "UI ini mesti berjalan di dalam shell desktop.",
  appUnavailableTitle: "Tidak Tersedia",
  navThemeGroup: "Tema",
  skipToContent: "Langkau ke kandungan",
  toast: {
    region: "Pemberitahuan",
    dismiss: "Tutup",
    finished: "Siap",
    failed: "Gagal",
    removed: "Dipadam daripada sejarah.",
    cleared: "Sejarah dikosongkan.",
    queued: "Dalam baris untuk dimuat turun.",
    finishedSummary: "{done} siap · {failed} gagal.",
  },
  status: {
    activeCount: "{count} aktif",
    ready: "Sedia",
    working: "Bekerja…",
    pausedResume: "{count} jeda dari sesi lalu — sambung semula?",
    offline: "Offline — muat turun sambung bila online semula.",
    recoverySettings: "Tetapan rosak, jadi ia ditetapkan semula.",
    recoveryQueue: "Barisan muat turun rosak, jadi ia dikosongkan.",
    recoveryWatchlist: "Senarai pantau rosak, jadi ia dikosongkan.",
    recoveryKept: "Fail lama disimpan sebagai {backup}.",
  },
  engine: {
    video: "Video",
    images: "Imej",
    auto: "Auto",
    videoOnly: "Video (yt-dlp)",
    imagesOnly: "Imej (gallery-dl)",
    tryOther: "Cuba enjin lain",
    downloadBoth: "Muat turun kedua-dua",
    unsupported: "Pautan ini tidak disokong oleh mana-mana enjin.",
    interrupted: "Terganggu — sambung untuk cuba lagi",
    partial: "Separa",
    probing: "Mengesan…",
    galleryNeedsBinary: "gallery-dl belum dipasang. Jalankan semakan Tools untuk pasang.",
    packNeedsBinary: "Enjin ini pek pilihan dan belum dipasang. Buka Tetapan → Pek Alatan untuk pasang.",
  },
  mini: {
    title: "Mod mini",
    exit: "Keluar mini",
    empty: "Tiada yang berjalan.",
  },
  home: {
    title: "Utama",
    urlLabel: "URL Video",
    urlPlaceholder: "Tampal pautan…",
    paste: "Tampal",
    analyze: "Analisis",
    quickDownload: "Muat turun pantas",
    analyzing: "Menganalisis…",
    cancelAnalyze: "Batal",
    reanalyze: "Analisis semula",
    watchClipboard: "Pantau papan klip",
    dropHint: "Petua: anda juga boleh seret-dan-lepas pautan ke sini.",
    shortcutsHint: "Pintasan: Ctrl+V tampal dan analisis · Ctrl+K perintah · Ctrl+, buka Tetapan · ? senarai pintasan.",
    invalidUrl: "Pautan itu tidak sah.",
    analyzeFailed: "Pautan ini tidak dapat dianalisis. Lihat Log.",
    previewDuration: "Tempoh",
    unknownDuration: "—",
    kindVideo: "Video",
    kindAudio: "Audio",
    advancedFormats: "Format lanjutan",
    useFormat: "Guna",
    presetCompatible: "MP4 Serasi",
    sizeUnknown: "-",
    entriesSelected: "dipilih",
    selectAll: "Semua",
    selectNone: "Tiada",
    queueSelected: "Muat turun yang dipilih",
    queueSingle: "Muat turun",
    queuedToast: "Diberatur {count}.",
    multiToBatch: "Dikesan {count} pautan — ditambah ke Kelompok di bawah.",
    inputMode: "Mod input pautan",
    modeSingle: "Pautan tunggal",
    modeBatch: "Kelompok",
    downloadRemaining: "Muat turun baki ({n})",
    upgradeHint: "Sudah ada dalam Pustaka anda ({preset}) — baris semula untuk naik taraf.",
    lowDiskConfirm: "Ruang tinggal {free} — teruskan baris?",
    playlistPresetNote: "Pratetap di atas terpakai untuk setiap entri yang dipilih.",
    liveBadge: "LANGSUNG",
    upcomingBadge: "AKAN DATANG",
    streamlinkHint: "Siaran langsung — Streamlink merakamnya lebih andal.",
    streamlinkCapture: "Rakam dengan Streamlink",
    streamlinkDismiss: "Tutup",
    wasLiveBadge: "PERNAH LANGSUNG",
    liveFromStart: "Rakam dari awal",
    waitForVideo: "Tunggu siaran bermula",
    splitChapters: "Pisahkan mengikut bab",
    metadata: "Metadata",
    metaTitle: "Tajuk",
    metaArtist: "Seniman",
    metaAlbum: "Album",
    metaYear: "Tahun",
    metadataHint: "Ditulis ke dalam tag fail. Biarkan kosong untuk melangkau.",
    perJobProxy: "Proksi (muat turun ini)",
    perJobProxyHint: "Kosong = guna tetapan proksi global.",
    chaptersCount: "{count} bab",
    chaptersList: "Bab ({count})",
    engineOverride: "Enjin",
    galleryTitle: "Galeri imej",
    galleryCount: "{count} imej",
    galleryDownloadAll: "Muat turun semua",
    galleryDownloadSelected: "Muat turun yang dipilih",
    galleryProbing: "Menyemak galeri…",
    galleryCheck: "Semak galeri imej",
    galleryEmpty: "Tiada imej di sini.",
    trimStart: "Mula potongan",
    trimEnd: "Tamat potongan",
    trimHint: "Bahagian mula–tamat (saat atau MM:SS). Kosong = seluruh video.",
    reverseEntries: "Balikkan",
    presetSummary: "Pratetap: {preset}",
  },
  batch: {
    title: "Kelompok",
    description: "Tampal banyak pautan sekali gus, atau lepaskan fail .txt. Satu pautan sebaris.",
    inputLabel: "Pautan (satu sebaris)",
    inputPlaceholder: "https://…\nhttps://…",
    add: "Tambah",
    chooseFile: "Pilih .txt…",
    pasteClipboard: "Tampal papan klip",
    analyzeAll: "Analisis semua",
    analyzing: "Menganalisis…",
    stop: "Berhenti",
    queueAllReady: "Baris semua yang sedia",
    queueing: "Mebarisi…",
    retryFailed: "Cuba semula yang gagal",
    remove: "Buang",
    expand: "Kembangkan",
    clear: "Padam",
    useGlobalPreset: "Guna pratetap global",
    useGlobalContainer: "Bekas lalai",
    presetLabel: "Pratetap",
    empty: "Tiada apa-apa lagi. Tampal pautan atau pilih fail .txt.",
    nothingFound: "Tiada pautan ditemui dalam teks itu — satu pautan penuh setiap baris.",
    needLinks: "Tambah pautan dahulu, kemudian analisis.",
    needReady: "Analisis pautan dahulu, kemudian bariskan.",
    analyzedAll: "Semua pautan telah dianalisis.",
    readyToQueue: "{n} dianalisis dan sedia — bariskan sekarang.",
    invalidSkipped: "Baris tidak sah dilangkau: {n}",
    duplicatesSkipped: "Duplikat dilangkau: {n}",
    truncatedNote: "Berhenti pada 500 baris; selebihnya diabaikan.",
    fileTooBig: "Fail itu melebihi 1 MB.",
    statusPending: "Menunggu",
    statusAnalyzing: "Menganalisis…",
    statusReady: "Sedia",
    statusFailed: "Gagal",
    queuedToast: "Diberatur {count}.",
  },
  playlist: {
    downloaded: "Dimuat turun",
    archived: "Diarkib",
    hideDownloaded: "Sembunyikan yang dimuat turun",
    filterPlaceholder: "Tapis entri…",
    checking: "Menyemak yang dimuat turun…",
  },
  duplicate: {
    title: "Sudah dimuat turun?",
    queueMessage: "Pautan ini sudah ada dalam baris gilir anda.",
    historyMessage: "Anda pernah memuat turun ini.",
    downloadedOn: "Dimuat turun:",
    skip: "Langkau",
    downloadAnyway: "Muat turun juga",
    openFile: "Buka fail sedia ada",
  },
  downloads: {
    title: "Muat Turun",
    empty: "Tiada apa-apa lagi. Bariskan sesuatu dari Utama.",
    goHome: "Pergi ke Utama",
    pause: "Jeda",
    resume: "Sambung",
    cancel: "Batal",
    retry: "Cuba semula",
    retryAll: "Cuba semula semua yang gagal",
    retryIn: "Cuba semula dalam {n}s · percubaan {a}",
    attempt: "Percubaan {a}",
    openFile: "Buka fail",
    showInFolder: "Tunjuk dalam folder",
    showFolder: "Buka folder",
    pauseAll: "Jeda semua",
    resumeAll: "Sambung semua",
    cancelQueued: "Batalkan yang berbaris",
    cancelledNote: "{count} berbaris dibatalkan.",
    clearedNote: "{count} dipadam.",
    undo: "Buat asal",
    clearFinished: "Padam yang siap",
    bulkActions: "Tindakan kelompok baris gilir",
    recording: "Merakam",
    stopRecording: "Henti merakam",
    searchPlaceholder: "Cari muat turun…",
    filterAll: "Semua",
    filterActive: "Aktif",
    filterError: "Gagal",
    filterDone: "Siap",
    noMatch: "Tiada muat turun sepadan.",
    clearFilters: "Padam carian & penapis",
    saveSearch: "Simpan carian",
    savedSearches: "Tersimpan",
    recentSearches: "Terkini",
    removeSaved: "Buang",
    pin: "Pin",
    unpin: "Nyahpin",
    pinned: "Dipin",
    priorityHigh: "Prioriti tinggi",
    priorityNormal: "Prioriti biasa",
    priorityLow: "Prioriti rendah",
    priorityCycle: "Prioriti: {label}",
    selectedCount: "{n} dipilih",
    clearSelection: "Padam pilihan",
    bulkPause: "Jeda yang dipilih",
    bulkResume: "Sambung yang dipilih",
    bulkRetry: "Cuba semula yang dipilih",
    bulkCancel: "Batalkan yang dipilih",
    copyLinks: "Salin pautan",
    linksCopied: "Pautan disalin.",
    throttleLabel: "Laju",
    throttleUnlimited: "Tanpa had",
    throttleNote: "Untuk muat turun baru.",
    queueEta: "ETA baris {eta} · baki {size}",
    schedule: "Jadual…",
    applySchedule: "Tetap",
    startsAt: "Mula {when}",
    clearSchedule: "Padam",
    reprocess: "Jalankan semula pasca-proses",
    postRunning: "Pasca-proses sedang berjalan untuk fail ini.",
    postDone: "Pasca-proses selesai.",
    postSaved: "Dijimatkan {size}.",
    postFailed: "Pasca-proses gagal.",
    postNothing: "Tiada untuk diproses.",
    postTagLow: "Padanan terbaik “{title}” skor {score} — gunakannya?",
    postTagApply: "Guna juga",
    postMenuConvert: "Tukar imej",
    postMenuTag: "Tag fail audio",
    postMenuCompress: "Mampatkan video",
    postMenuTranscribe: "Transkrip audio (.srt)",
    postMenuUpload: "Muat naik via rclone",
    postMenuReprocess: "Jalankan semula pasca-proses",
    postMenuMediaInfo: "Maklumat media",
    galleryFiles: "{count} fail",
    gallerySkipped: "{count} dilangkau",
    galleryFailed: "{count} gagal",
    rerunGallery: "Jalankan semula (langkau yang siap)",
    stalled: "Tersekat — tiada output buat seketika",
    restart: "Mula semula",
    outdatedBanner: "Ada muat turun gagal: enjin nampaknya lapuk.",
    outdatedUpdate: "Kemas kini & cuba semua",
  },
  stats: {
    title: "Statistik",
    empty: "Tiada muat turun direkodkan lagi.",
    completed: "Selesai",
    failed: "Gagal",
    totalSize: "Jumlah saiz",
    totalDuration: "Jumlah masa",
    perWeek: "Setiap minggu",
    topUploaders: "Pemuat naik teratas",
    presetMix: "Pratetapan",
    topSites: "Tapak teratas",
    presetSuccess: "Kejayaan ikut pratetap",
    storage: "Storan",
    cleanOrphans: "Bersihkan separa",
    storageCleaned: "Fail separa dibersihkan.",
    presetAdvice: "Ada pratetap kerap gagal — MP4 Serasi berfungsi hampir di mana-mana.",
    unknown: "tidak diketahui",
    noUploaders: "Tiada data pemuat naik lagi.",
    noData: "Tiada data lagi.",
    unknownNote: "{count} entri lama tiada saiz direkodkan.",
    derivedFromHistory:
      "Semua ini diperole daripada sejarah muat turun. Mengkosongkan sejarah akan mengosongkan angka ini.",
  },
  library: {
    title: "Pustaka",
    searchPlaceholder: "Cari tajuk atau pautan…",
    filterKind: "Jenis",
    filterKindAll: "Semua jenis",
    filterKindVideo: "Video",
    filterKindAudio: "Audio",
    filterEngine: "Enjin",
    filterEngineAll: "Semua enjin",
    filterSite: "Tapak (cth. youtube)",
    sortLabel: "Susun",
    sortNewest: "Terkini",
    sortOldest: "Terlama",
    sortTitle: "Tajuk",
    sortSize: "Saiz",
    viewList: "Paparan senarai",
    viewGrid: "Paparan grid",
    gridCapped: "Memaparkan {n} pertama daripada {t} — sempitkan carian atau penapis.",
    loading: "Memuatkan…",
    empty: "Tiada muat turun siap lagi.",
    emptySearch: "Tiada padanan.",
    results: "{n} daripada {t} dipaparkan",
    redownload: "Muat turun semula",
    remove: "Buang",
    clearAll: "Padam semua",
    clearConfirm: "Buang semua entri sejarah?",
    redownloadConfirm: "Muat turun “{title}” semula? Fail sedia ada akan digantikan.",
    missing: "Fail tiada",
    locate: "Cari…",
    checking: "Menyemak fail…",
    preview: "Pratonton",
    previewLoading: "Memuatkan pratonton…",
    previewUnavailable: "Pratonton tiada untuk fail ini.",
    watchTitle: "Senarai Pantau",
    watchAdd: "Tambah channel",
    watchPlaceholder: "URL channel atau senarai…",
    watchCheck: "Semak",
    watchQueueNew: "Baris baharu ({n})",
    watchRemove: "Buang",
    watchEmpty: "Tiada channel dipantau lagi.",
    watchFirstCheck: "Asas ditetapkan — muat naik baharu akan muncul di sini.",
    watchNew: "{n} baharu",
    watchLastChecked: "Semakan akhir: {when}",
    watchModeAuto: "Muat turun auto",
    watchModeNotify: "Maklum sahaja",
    watchPaused: "Dijeda",
    watchPause: "Jeda",
    watchResume: "Sambung",
    watchInterval: "Setiap {n} min",
    watchFolder: "Folder…",
    watchAutoDisabled: "Berhenti selepas gagal berulang — sambung untuk cuba lagi.",
    watchCapConfirm: "{n} item baharu dalam “{title}” — bariskan semua?",
    watchAutoQueued: "Dibariskan {n} baharu dari “{title}”.",
    watchNotifyNew: "{n} baharu dalam “{title}”.",
    previewPip: "Gambar-dalam-gambar",
    previewFullscreen: "Skrin penuh",
    mediaDetails: "Butiran media",
    mediaFormat: "Bekas",
    mediaDuration: "Tempoh",
    mediaSize: "Saiz",
    mediaVideo: "Video",
    mediaAudio: "Audio",
    mediaNoInfo: "Tiada maklumat media.",
  },
  settings: {
    title: "Tetapan",
    loading: "Memuatkan…",
    downloadDir: "Folder muat turun",
    browse: "Layari…",
    filenameTemplate: "Templat nama fail",
    filenamePresets: "Pratetap",
    templatePreview: "Pratonton: {name}",
    templateInvalid: "Templat mesti mengandungi %(ext)s.",
    speedInvalid: "Guna kadar seperti 4.2M, atau kosongkan untuk tanpa had.",
    concurrency: "Muat turun serentak (1–5)",
    analyzeTimeout: "Masa tamat analisis (saat, 10–300)",
    speedLimit: "Had laju (cth. 4.2M, kosong = tanpa had)",
    proxy: "Proksi (kosong = terus)",
    concurrencyGallery: "Muat turun imej serentak (1–5)",
    downloadWindowStart: "Mula tetingkap muat turun (HH:MM, kosong = sentiasa)",
    downloadWindowEnd: "Tamat tetingkap muat turun (HH:MM, kosong = sentiasa)",
    windowInvalid: "Guna HH:MM 24-jam, atau biarkan kosong.",
    cookies: "Kuki dari pelayar (cth. chrome, kosong = mati)",
    cookiesFile: "Fail kuki (.txt, kosong = mati)",
    embedThumbnail: "Benamkan gambar kecil",
    embedMetadata: "Benamkan metadata",
    subtitles: "Muat turun sari kata",
    subtitleLangs: "Bahasa sari kata",
    embedSubs: "Benamkan sari kata",
    includeAutoSubs: "Sertakan sari kata auto-janaan",
    mergeContainer: "Bekas output",
    mergeContainerHint:
      "Untuk muat turun video. Setiap bekas di sini boleh dihasilkan atau ditukar oleh yt-dlp yang disertakan.",
    postTitle: "Selepas muat turun",
    ppConvert: "Tukar imej (JPG/PNG)",
    ppFormat: "Format imej",
    ppQuality: "Kualiti imej (1–100)",
    ppMaxDim: "Sisi imej maks (px)",
    ppStripExif: "Buang metadata EXIF/GPS",
    ppPackage: "Bungkus galeri",
    ppPackageOff: "Mati",
    ppUgoira: "Tukaran animasi Pixiv",
    ppUgoiraOff: "Mati",
    ppAutoTag: "Tag audio auto (MusicBrainz)",
    ppAutoTagHint: "Padanan yakin tinggi sahaja; perlu internet.",
    ppCompress: "Mampatkan video selepas muat turun",
    ppCompressOff: "Mati",
    ppCompressSmall: "Kecil",
    ppCompressBalanced: "Seimbang",
    ppCompressArchive: "Arkib",
    ppTranscribe: "Transkrip audio ke sari kata (.srt, whisper, CPU)",
    ppTranscribeHint: "Perlu pek whisper + model di bawah (eksperimen).",
    ppWhisperModel: "Model whisper",
    ppRcloneRemote: "Folder jauh rclone (cth. myremote:backups/)",
    ppRcloneRemoteHint: "rclone memiliki konfigurasinya — FluxDL hanya simpan laluan ini, bukan kelayakan.",
    ppAutoUpload: "Muat naik fail siap auto via rclone",
    ppKeepOriginals: "Simpan fail asal",
    ppKeepOriginalsHint: "Mati alih fail asal ke Recycle Bin.",
    packsTitle: "Pek Alatan",
    packNotInstalled: "Belum dipasang",
    packInstalled: "Terpasang {v}",
    packInstall: "Pasang",
    packUpdate: "Kemas kini ke {v}",
    packUpdateAll: "Kemas kini semua",
    packCheckUpdates: "Semak kemas kini",
    packRemove: "Buang",
    packUpToDate: "Terkini",
    packSize: "Muat turun ≈ {size}",
    packDiskUsed: "Di cakera: {size}",
    packLicense: "Lesen: {license}",
    packVerified: "Disahkan SHA256SUMS",
    packConsent: "Saya faham projek ini tidak menerbitkan fail checksums",
    packModels: "Model pertuturan",
    packModelInstall: "Muat turun",
    packModelRemove: "Buang",
    packWorking: "Bekerja…",
    packCancel: "Batal",
    packDone: "Siap.",
    packFailed: "Operasi pek gagal.",
    pacingTitle: "Irama sopan",
    pacingRequests: "Kelewatan antara permintaan halaman (s)",
    pacingMin: "Kelewatan minimum sebelum setiap muat turun (s)",
    pacingMax: "Kelewatan maksimum sebelum setiap muat turun (s)",
    pacingSubs: "Kelewatan sebelum setiap muat turun sarikata (s)",
    pacingHint:
      "Kosong = mati. Menaikkan nilai ini menjadikan muat turun nampak seperti tontonan biasa dan bukan scrape, lalu mengurangkan kemungkinan platform mengehadkan IP anda (HTTP 429). Lebih perlahan, tetapi lebih selamat.",
    pacingOff: "Mati",
    pacingLight: "Light",
    pacingStandard: "Standard",
    containerLabel: "Bekas",
    containerDefault: "Default (from Settings)",
    codecPreference: "Codec video pilihan",
    codecAuto: "Auto (lalai tapak)",
    codecH264: "H.264 (boleh main di mana-mana)",
    codecVp9: "VP9",
    codecAv1: "AV1 (fail lebih kecil)",
    thumbnailAccent: "Warnakan pratonton ikut gambar kecil",
    skipArchived: "Langkau video senarai yang sudah diarkib",
    playlistSubfolder: "Muat turun senarai ke dalam subfolder",
    clearArchive: "Padam arkib…",
    backup: "Sandaran & pulih",
    exportBackup: "Eksport sandaran…",
    importBackup: "Import sandaran…",
    backupDone: "Sandaran dipulihkan ({q} baris, {h} sejarah, {w} dipantau, {d} dibuang).",
    backupFailed: "Fail sandaran itu tidak dapat dibaca.",
    archiveCleared: "Arkib dipadamkan.",
    archiveConfirm: "Lupakan semua video yang diarkib? Senarai akan memuat turunnya semula.",
    sponsorBlock: "Buang segmen SponsorBlock",
    theme: "Tema",
    themes: {
      obsidian: "Obsidian",
      midnight: "Midnight",
      ember: "Ember",
      paper: "Paper",
    },
    density: "Kepadatan",
    densityComfortable: "Selesa",
    densityCompact: "Padat",
    accent: "Warna aksen",
    accentCustom: "Heks tersuai (#rrggbb)",
    accentReset: "Kembali ke lalai tema",
    accentWarning: "Kontras rendah pada teks aksen — diselaraskan automatik.",
    postAction: "Selepas muat turun",
    postNone: "Jangan buat apa-apa",
    postOpen: "Buka fail",
    postReveal: "Tunjuk dalam folder",
    language: "Bahasa",
    languageAuto: "Auto (sistem)",
    languageEnglish: "English",
    languageMalay: "Bahasa Melayu",
    historyLimit: "Simpan entri sejarah (10–5000)",
    autoCheckUpdate: "Semak kemas kini enjin semasa mula",
    notifyFinished: "Notifikasi sistem untuk muat turun siap",
    crashReports: "Simpan laporan ranap tempatan (ikut serta, tidak dimuat naik)",
    profiles: "Profil satu klik",
    experimental: "Ciri uji kaji (boleh berubah atau rosak)",
    sectionDownloads: "Muat turun",
    sectionQuality: "Kualiti",
    sectionSubtitles: "Sari kata",
    sectionNetwork: "Rangkaian",
    sectionAppearance: "Rupa",
    sectionBehavior: "Selepas muat turun & tetingkap",
    sectionPresets: "Pratetap",
    sectionData: "Data & sandaran",
    followSystemTheme: "Ikut mod cerah/gelap sistem",
    launchAtLogin: "Mula bersama Windows (minimized ke tray)",
    autoSort: "Isih ke folder Muzik / Video",
    profilesHint: "Pakai berkas tetapan serta-merta.",
    profileMusic: "Muzik",
    profileVideo: "Video",
    profileArchive: "Arkib audio",
    closeBehavior: "Tindakan butang Tutup (X)",
    closeTray: "Sembunyi ke tray (muat turun berterusan)",
    closeQuit: "Keluar app",
    minimizeToTray: "Butang minimize juga sembunyi ke tray",
    saved: "Disimpan.",
    saveFailed: "Tidak dapat menyimpan: {detail}",
    search: "Cari tetapan…",
    clearSearch: "Padam carian",
    noMatch: "Tiada tetapan sepadan.",
    matchCount: "{n} daripada {t} tetapan",
    routerMode: "Enjin muat turun",
    autoUpdateTools: "Kemas kini alatan automatik semasa melahu",
    downloadRetries: "Cuba semula rangkaian (kosong = lalai alatan)",
    concurrentFragments: "Fragmen serentak (kosong = lalai alatan)",
    socketTimeoutSec: "Tamat masa soket, saat (kosong = lalai alatan)",
    useAria2c: "Guna pemuat turun aria2c jika ada",
    sponsorCats: "Kategori SponsorBlock",
    sponsorCatsHint: "Senarai koma, cth. all,-filler. Terpakai bila pembuangan dihidupkan.",
    customFormat: "Pemilih format tersuai (-f, kosong = mati)",
    customFormatHint: "Nilai -f yt-dlp lanjutan. Format setiap pautan masih diutamakan.",
    toolsTitle: "Alatan & Enjin",
    toolsUpdate: "Kemas kini",
    toolsReinstall: "Pasang semula",
    toolsRollback: "Undur",
    toolsUpdateAll: "Kemas kini semua",
    toolsRunDoctor: "Jalankan semakan kesihatan",
    toolsChannel: "Saluran yt-dlp",
    toolsLastChecked: "Terakhir disemak {when}",
    toolsNeverChecked: "Belum pernah disemak",
    toolsMissing: "Tiada",
    toolsUpdated: "Alatan dikemas kini.",
    toolsDoctorOk: "Semua semakan lulus.",
    toolsInstallGuide: "Letakkan {exe} dalam folder bin aplikasi atau pada PATH.",
    toolsOpenSettings: "Lihat {section} dalam Tetapan.",
    sectionImages: "Imej (gallery-dl)",
    imagesDownloadDir: "Folder imej (kosong = Downloads/Images)",
    imagesFolderTemplate: "Templat folder galeri",
    imagesFilenameTemplate: "Templat nama fail imej",
    imagesArchive: "Langkau imej yang sudah dimuat turun (arkib)",
    imagesSidecar: "Simpan sidecar metadata (.json)",
    imagesCustom: "Gantian konfigurasi mentah (JSON, kosong = janaan)",
    imagesCustomHint: "Menggantikan konfigurasi gallery-dl yang dijana. Set semula memulihkan yang dijana.",
    imagesCustomReset: "Set semula kepada janaan",
    imagesCustomInvalid: "Tidak disimpan: {detail}",
    remoteTitle: "Akses jauh",
    remoteHint:
      "Kawal FluxDL daripada pelayar atau sambungan di komputer ini. Loopback sahaja — permintaan tidak keluar dari PC ini.",
    remoteEnable: "Hidupkan pelayan API tempatan (127.0.0.1)",
    remotePort: "Port",
    remoteRunning: "Berjalan di 127.0.0.1:{port}.",
    remoteStopped: "Berhenti.",
    remoteErrEncryption: "Storan token tidak tersedia (penyulitan OS dimatikan) — pelayan tidak boleh bermula.",
    remoteErrBind: "Tidak dapat mengikat port — adakah salinan lain sedang berjalan?",
    remoteErrUnknown: "Ralat pelayan: {detail}",
    remoteCopyLink: "Salin pautan pasangan",
    remoteCopied: "Pautan pasangan disalin.",
    remoteCopyFailed: "Tidak dapat menyalin pautan.",
    remoteRotate: "Putar token",
    remoteRotateConfirm:
      "Keluarkan token baharu? Pelayar dan sambungan yang dipasangkan berhenti berfungsi sehingga anda memasangkannya semula.",
    remoteRotated: "Token baharu dikeluarkan. Pasangkan semula peranti anda.",
    remoteRefresh: "Muat semula status",
    remoteLanNote: "Akses LAN pilihan ikut serta — baca amaran dahulu.",
    notifyTitle: "Pemberitahuan",
    notifyDiscord: "Webhook Discord bila siap/gagal",
    notifyWebhook: "URL webhook (disimpan disulitkan)",
    notifyTelegram: "Mesej Telegram bila siap/gagal",
    notifyChatId: "ID Sembang",
    notifyToken: "Token bot (disimpan disulitkan)",
    notifyTest: "Hantar ujian",
    notifyClear: "Padam",
    notifySent: "Ujian dihantar.",
    notifyFailed: "Pemberitahuan gagal.",
    lanEnable: "Benarkan akses LAN",
    lanWarn: "Mana-mana peranti di rangkaian anda yang ada token boleh membaris dan membatalkan muat turun. Guna senarai dibenar dan nyahaktif automatik.",
    lanConfirm: "Dedahkan API kepada rangkaian tempatan? Sesiapa dengan token boleh menambah dan membatalkan muat turun.",
    lanAllowlist: "Senarai IP dibenar (awalan koma, kosong = semua LAN)",
    lanAutoDisable: "Nyahaktif automatik selepas jam (kosong = kekal hidup)",
    lanOn: "LAN dibuka — token diputar. Pasangkan semula.",
    remoteAudit: "Muat turun log audit",
  },
  logs: {
    title: "Log & Perihal",
    engineVersions: "Versi enjin",
    appVersion: "App",
    ytdlpVersion: "yt-dlp",
    ffmpegVersion: "ffmpeg",
    checkUpdate: "Semak kemas kini",
    updating: "Mengemas kini…",
    upToDate: "Enjin sudah terkini.",
    checkUpdates: "Semak kemas kini",
    checkingUpdates: "Menyemak…",
    appUpToDate: "FluxDL terkini ({v}).",
    appUpdateReady: "FluxDL {v} tersedia (anda ada {cur}).",
    appReleased: "Diterbitkan {date}.",
    ytdlpUpToDate: "yt-dlp terkini ({v}).",
    ytdlpUpdateReady: "yt-dlp {v} tersedia — guna “Semak kemas kini” untuk memasangnya.",
    updateCheckFailed: "Tidak dapat hubungi pelayan kemas kini (offline?).",
    getUpdate: "Dapatkan kemas kini",
    updateFailed: "Kemas kini gagal. Lihat di bawah.",
    repairEngine: "Baiki enjin",
    repairing: "Membaiki…",
    repaired: "Enjin disahkan.",
    repairFailed: "Pembaikan gagal. App mungkin perlu dipasang semula.",
    viewLog: "Lihat",
    logPlaceholder: "Pilih kerja untuk melihat log enjin mentahnya.",
    reportBug: "Laporkan pepijat",
    crashTitle: "Laporan ranap",
    crashClear: "Padam",
    crashEmpty: "Tiada laporan ranap direkodkan.",
    noticesTitle: "Notis pihak ketiga",
    search: "Cari log…",
    clearSearch: "Padam carian",
    errorsOnly: "Ralat sahaja",
    follow: "Ikuti log langsung",
    refresh: "Muat semula",
    copyLog: "Salin log",
    logCopied: "Log disalin.",
    showCommand: "Tunjuk perintah",
    selectJobFirst: "Pilih kerja di atas untuk melihat baris perintahnya.",
    matchCount: "{n} baris sepadan",
    noMatch: "Tiada baris sepadan.",
    copyrightNote:
      "Anda bertanggungjawab menghormati hak cipta dan syarat setiap tapak. Muat turun hanya kandungan milik anda atau yang dibenarkan.",
  },
  safety: {
    exeMessage: "Fail ini boleh menjalankan program pada PC anda. Buka “{name}”?",
    exeOpen: "Buka",
    exeCancel: "Batal",
  },
  closeConfirm: {
    title: "Muat turun masih berjalan?",
    message: "{count} muat turun masih aktif. Keluar mengekalkan fail separa untuk sambungan semula.",
    quit: "Keluar juga",
    hide: "Sembunyi ke tray",
    cancel: "Batal",
  },
  tasks: {
    newDownload: "Muat turun baharu",
    newDownloadDesc: "Buka FluxDL untuk menambah muat turun",
    openFolder: "Buka folder muat turun",
    openFolderDesc: "Tunjuk folder muat turun",
  },
  errors: {
    viewCrashed: "Paparan ini ranap.",
    viewCrashedHint: "Muat turun anda berjalan seperti biasa — cuma skrin ini perlu dimuat semula.",
    reloadView: "Muat semula paparan",
    actionRetry: "Cuba semula",
    actionTryNm3u8dl: "Cuba dengan N_m3u8DL-RE",
    actionFailed: "Tindakan itu gagal. Lihat Log untuk butiran.",
    actionUpdateRetry: "Kemas kini enjin & cuba semula",
    actionCookiesOnce: "Guna sekali",
    actionCookiesAlways: "Sentiasa guna",
    actionRepair: "Baiki enjin",
    actionSettings: "Buka tetapan",
    actionLogs: "Buka log",
    actionFolder: "Pilih folder",
    cookiesLabel: "Baca kuki dari",
    updateBlockedBusy: "Jeda atau habiskan muat turun aktif dahulu, kemudian kemas kini.",
    engineUpdated: "Enjin dikemas kini. Mencuba semula…",
    engineRepairing: "Membaiki…",
    engineRepaired: "Enjin dibaiki dan disahkan.",
    engineRepairFailed: "Pembaikan gagal. Lihat Log.",
  },
  browsers: {
    chrome: "Google Chrome",
    edge: "Microsoft Edge",
    firefox: "Firefox",
    brave: "Brave",
    chromium: "Chromium",
    opera: "Opera",
    vivaldi: "Vivaldi",
    whale: "Whale",
  },
  menu: {
    label: "Tindakan muat turun",
    copyUrl: "Salin URL",
    copyPath: "Salin path fail",
    retryPreset: "Cuba semula dengan pratetap lain…",
    moveUp: "Gerak ke atas",
    moveDown: "Gerak ke bawah",
    remove: "Buang dari senarai",
    deleteFile: "Padam fail",
    deleteFolder: "Padam folder",
    deleteConfirm: "Alihkan fail ini ke Recycle Bin? Entri sejarah dikekalkan.",
    deleteFolderConfirm: "Alihkan folder ini ke Recycle Bin? Entri sejarah dikekalkan.",
    deletedToast: "Dialih ke Recycle Bin.",
    fileDeleted: "Fail dipadamkan",
    folderDeleted: "Folder dipadamkan",
    copyFailed: "Salinan gagal.",
  },
  diagnostics: {
    copy: "Salin diagnostik",
    save: "Simpan .txt",
    includeUrls: "Sertakan URL (mungkin mengandungi pautan peribadi)",
    preview: "Pratonton laporan",
    copied: "Diagnostik disalin.",
    saved: "Diagnostik disimpan.",
    reportTitle: "Diagnostik FluxDL",
    reportVersions: "Versi",
    reportSettings: "Tetapan (diredaksi)",
    reportErrors: "Ralat terkini",
    reportNoErrors: "(tiada)",
    reportLog: "Ekor log",
    reportNoLog: "(tiada log dipilih)",
    reportCrashes: "Laporan ranap (ikut serta, tempatan sahaja)",
  },
  commands: {
    title: "Palet perintah",
    placeholder: "Taip perintah…",
    empty: "Tiada perintah sepadan.",
    smartAction: "Tindakan pintar",
    pasteAnalyze: "Tampal URL papan klip dan analisis",
    goHome: "Pergi ke Utama",
    goDownloads: "Pergi ke Muat Turun",
    goLibrary: "Pergi ke Pustaka",
    goStats: "Pergi ke Statistik",
    goSettings: "Pergi ke Tetapan",
    goLogs: "Pergi ke Log",
    goChangelog: "Pergi ke Log Perubahan",
    themeObsidian: "Tukar ke tema Obsidian",
    themeMidnight: "Tukar ke tema Midnight",
    themePaper: "Tukar ke tema Paper (cerah)",
    themeEmber: "Tukar ke tema Ember",
    updateEngine: "Kemas kini enjin yt-dlp",
    openDownloadsFolder: "Buka folder muat turun",
    pauseAll: "Jeda semua muat turun",
    resumeAll: "Sambung semua muat turun",
    retryAll: "Cuba semula semua muat turun yang gagal",
    showShortcuts: "Tunjuk pintasan papan kekunci",
    clearFinished: "Padam muat turun yang siap",
    toggleDensity: "Tukar ketumpatan selesa/padat",
    toggleMiniMode: "Tukar mod mini (sentiasa di atas)",
    settingsFolder: "Buka Tetapan: folder muat turun",
    settingsCookies: "Buka Tetapan: kuki",
    settingsProxy: "Buka Tetapan: proksi",
  },
  shortcuts: {
    title: "Pintasan papan kekunci",
    close: "Tutup",
    paste: "Tampal pautan papan klip dan analisis",
    palette: "Buka palet perintah",
    settings: "Buka Tetapan",
    miniMode: "Tukar mod mini",
    navigate: "Lompat antara paparan (Ctrl+1…7)",
    help: "Buka senarai pintasan ini",
    dismiss: "Tutup dialog",
  },
  changelog: {
    title: "Log Perubahan",
    readMore: "Baca lagi",
    showLess: "Tutup",
  },
  updateModal: {
    title: "Kemas kini tersedia",
    version: "FluxDL {v} tersedia",
    installed: "Terpasang: {cur}",
    published: "Diterbitkan {date}",
    setupSize: "Pemasang Setup · {size} (pasang automatik)",
    portableSize: "Portable · {size} (manual)",
    notes: "Apa yang baharu",
    noNotes: "Lihat tab Log Perubahan selepas mengemas kini.",
    download: "Muat turun & pasang",
    later: "Nanti",
    skip: "Langkau versi ini",
    downloading: "Memuat turun… {received} daripada {total}",
    downloadingUnknown: "Memuat turun… {received}",
    installing: "Muat turun siap — memasang versi baharu…",
    failed: "Muat turun gagal: {detail}",
    retry: "Cuba semula",
    ytdlpNote: "yt-dlp juga ada kemas kini — lihat Log.",
  },
  onboarding: {
    title: "Selamat datang ke FluxDL",
    subtitle: "Tiga langkah pantas — anda boleh ubah semuanya kemudian dalam Tetapan.",
    stepFolder: "Muat turun patut pergi ke mana?",
    browse: "Layari…",
    stepTheme: "Pilih tema",
    stepPreset: "Pratetap lalai",
    engineOk: "Enjin sedia",
    engineFail: "Semakan enjin gagal — anda masih boleh guna app.",
    back: "Kembali",
    next: "Seterusnya",
    done: "Siap",
    skip: "Langkau",
    replay: "Ulangi onboarding",
  },
};

/** Default (English) dictionary — existing STRINGS imports keep working. */
export const STRINGS: Strings = EN;

/** Bahasa Melayu dictionary (key parity enforced by Parity<Strings>). */
export const STRINGS_MS: Parity<Strings> = MS;
