/**
 * All user-facing strings in one file (EN first). Screens reference
 * STRINGS.* instead of inline literals so a second locale is a pure add.
 */
export const STRINGS = {
  appUnavailable: "This UI must run inside the desktop shell.",
  appUnavailableTitle: "Unavailable",
  navThemeGroup: "Theme",
  skipToContent: "Skip to content",
  toast: {
    region: "Notifications",
    dismiss: "Dismiss",
    finished: "Finished",
    failed: "Failed",
    removed: "Removed from history.",
    cleared: "History cleared.",
  },
  status: {
    active: "active",
    ready: "Ready",
  },
  home: {
    title: "Home",
    urlLabel: "Video URL",
    urlPlaceholder: "Paste a link…",
    paste: "Paste",
    analyze: "Analyze",
    analyzing: "Analyzing…",
    watchClipboard: "Watch clipboard",
    dropHint: "Tip: you can also drag-drop a link here.",
    shortcutsHint: "Shortcuts: Ctrl+V pastes and analyzes · Ctrl+K commands · Ctrl+, opens Settings.",
    invalidUrl: "That link does not look valid.",
    analyzeFailed: "Could not analyze this link. See Logs for details.",
    previewDuration: "Duration",
    unknownDuration: "—",
    kindVideo: "Video",
    kindAudio: "Audio",
    advancedFormats: "Advanced formats",
    useFormat: "Use",
    presetCompatible: "Compatible MP4",
    sizeUnknown: "-",
    sizeNote: "Sizes are estimates from analyzed formats.",
    entriesSelected: "selected",
    selectAll: "All",
    selectNone: "None",
    queueSelected: "Download selected",
    queueSingle: "Download",
    queuedToast: "Queued.",
    playlistPresetNote: "The preset above applies to every selected entry.",
  },
  batch: {
    title: "Batch",
    description: "Paste many links at once, or drop a .txt file. One link per line.",
    inputLabel: "Links (one per line)",
    inputPlaceholder: "https://…\nhttps://…",
    add: "Add",
    chooseFile: "Choose .txt…",
    analyzeAll: "Analyze all",
    analyzing: "Analyzing…",
    queueAllReady: "Queue all ready",
    queueing: "Queueing…",
    retryFailed: "Retry failed",
    remove: "Remove",
    expand: "Expand",
    clear: "Clear",
    useGlobalPreset: "Use global preset",
    presetLabel: "Preset",
    empty: "Nothing here yet. Paste links or choose a .txt file.",
    invalidSkipped: "Invalid lines skipped:",
    duplicatesSkipped: "Duplicates skipped:",
    truncatedNote: "Stopped at 500 lines; the rest was ignored.",
    fileTooBig: "That file is over 1 MB.",
    statusPending: "Pending",
    statusAnalyzing: "Analyzing…",
    statusReady: "Ready",
    statusFailed: "Failed",
    queuedToast: "Queued.",
  },
  duplicate: {
    title: "Already downloaded?",
    queueMessage: "This link is already in your queue.",
    historyMessage: "You downloaded this before.",
    downloadedOn: "Downloaded:",
    skip: "Skip",
    downloadAnyway: "Download anyway",
    openFile: "Open existing file",
  },
  downloads: {
    title: "Downloads",
    empty: "Nothing here yet. Queue something from Home.",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    retry: "Retry",
    openFile: "Open file",
    showInFolder: "Show in folder",
    showFolder: "Open folder",
    pauseAll: "Pause all",
    resumeAll: "Resume all",
    cancelQueued: "Cancel queued…",
    cancelQueuedConfirm: "Cancel every queued download? They will be kept in history.",
    clearFinished: "Clear finished",
    bulkActions: "Bulk queue actions",
  },
  library: {
    title: "Library",
    searchPlaceholder: "Search title or link…",
    loading: "Loading…",
    empty: "No finished downloads yet.",
    emptySearch: "No matches.",
    redownload: "Download again",
    remove: "Remove",
    clearAll: "Clear all",
    clearConfirm: "Remove all history entries?",
  },
  settings: {
    title: "Settings",
    loading: "Loading…",
    downloadDir: "Download folder",
    browse: "Browse…",
    filenameTemplate: "Filename template",
    filenamePresets: "Presets",
    concurrency: "Simultaneous downloads (1–5)",
    speedLimit: "Speed limit (e.g. 4.2M, empty = unlimited)",
    proxy: "Proxy (empty = direct)",
    cookies: "Cookies from browser (e.g. chrome, empty = off)",
    cookiesFile: "Cookies file (.txt, empty = off)",
    embedThumbnail: "Embed thumbnail",
    embedMetadata: "Embed metadata",
    subtitles: "Download subtitles",
    subtitleLangs: "Subtitle languages",
    embedSubs: "Embed subtitles",
    mergeContainer: "Merge container",
    codecPreference: "Preferred video codec",
    codecAuto: "Auto (site default)",
    codecH264: "H.264 (plays everywhere)",
    codecVp9: "VP9",
    codecAv1: "AV1 (smaller files)",
    skipArchived: "Skip playlist videos already in the archive",
    clearArchive: "Clear archive…",
    archiveCleared: "Archive cleared.",
    archiveConfirm: "Forget every archived video? Playlists will download them again.",
    sponsorBlock: "Remove SponsorBlock segments",
    theme: "Theme",
    postAction: "After download",
    postNone: "Do nothing",
    postOpen: "Open file",
    postReveal: "Show in folder",
    autoCheckUpdate: "Check engine updates on launch",
    saved: "Saved.",
  },
  logs: {
    title: "Logs & About",
    engineVersions: "Engine versions",
    appVersion: "App",
    ytdlpVersion: "yt-dlp",
    ffmpegVersion: "ffmpeg",
    checkUpdate: "Check for update",
    updating: "Updating…",
    upToDate: "Engine is up to date.",
    updateFailed: "Update failed. See below.",
    repairEngine: "Repair engine",
    repairing: "Repairing…",
    repaired: "Engine verified.",
    repairFailed: "Repair failed. The app may need reinstalling.",
    viewLog: "View",
    logPlaceholder: "Pick a job to inspect its raw engine log.",
    copyrightNote:
      "You are responsible for respecting copyright and each site's terms. Only download content you own or are allowed to keep.",
  },
  errors: {    actionRetry: "Retry",
    actionUpdateRetry: "Update engine & retry",
    actionCookiesOnce: "Use once",
    actionCookiesAlways: "Always use",
    actionRepair: "Repair engine",
    actionSettings: "Open settings",
    actionLogs: "Open logs",
    actionFolder: "Choose folder",
    cookiesLabel: "Read cookies from",
    updateBlockedBusy: "Pause or finish the active downloads first, then update.",
    engineUpdated: "Engine updated. Retrying…",
    engineRepairing: "Repairing…",
    engineRepaired: "Engine repaired and verified.",
    engineRepairFailed: "Repair failed. See Logs for details.",
  },
  browsers: {
    chrome: "Google Chrome",
    edge: "Microsoft Edge",
    firefox: "Firefox",
    brave: "Brave",
    chromium: "Chromium",
    opera: "Opera",
    vivaldi: "Vivaldi",
    whale: "Whale",
  },
  menu: {
    label: "Download actions",
    copyUrl: "Copy URL",
    copyPath: "Copy file path",
    retryPreset: "Retry with another preset…",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove from list",
    deleteFile: "Delete file",
    deleteConfirm: "Move this file to the Recycle Bin? The history entry is kept.",
    deletedToast: "Moved to the Recycle Bin.",
    fileDeleted: "File deleted",
    copyFailed: "Copy failed.",
  },
  diagnostics: {
    copy: "Copy diagnostics",
    save: "Save .txt",
    includeUrls: "Include URLs (they may contain private links)",
    preview: "Report preview",
    copied: "Diagnostics copied.",
    saved: "Diagnostics saved.",
    reportTitle: "FluxDL diagnostics",
    reportVersions: "Versions",
    reportSettings: "Settings (redacted)",
    reportErrors: "Recent errors",
    reportNoErrors: "(none)",
    reportLog: "Log tail",
    reportNoLog: "(no log selected)",
  },
  commands: {
    title: "Command palette",
    placeholder: "Type a command…",
    empty: "No matching commands.",
    pasteAnalyze: "Paste clipboard URL and analyze",
    goHome: "Go to Home",
    goDownloads: "Go to Downloads",
    goLibrary: "Go to Library",
    goSettings: "Go to Settings",
    goLogs: "Go to Logs",
    themeObsidian: "Switch to Obsidian theme",
    themeMidnight: "Switch to Midnight theme",
    themeEmber: "Switch to Ember theme",
    updateEngine: "Update yt-dlp engine",
    openDownloadsFolder: "Open downloads folder",
    pauseAll: "Pause all downloads",
    resumeAll: "Resume all downloads",
    clearFinished: "Clear finished downloads",
    settingsFolder: "Open Settings: download folder",
    settingsCookies: "Open Settings: cookies",
    settingsProxy: "Open Settings: proxy",
  },
} as const;

export type Strings = typeof STRINGS;
