/**
 * All user-facing strings in one file. EN is the source of truth; MS is
 * typed for key parity (a missing key fails typecheck). Screens read the
 * active dictionary via useStrings() (locale.ts) so a language switch
 * re-renders. strings.ts itself stays dependency-free (main imports it).
 */
const EN = {
  appUnavailable: "This UI must run inside the desktop shell.",
  appUnavailableTitle: "Unavailable",
  navThemeGroup: "Theme",
  skipToContent: "Skip to content",
  toast: {
    region: "Notifications",
    dismiss: "Dismiss",
    finished: "Finished",
    failed: "Failed",
    removed: "Removed from history.",
    cleared: "History cleared.",
  },
  status: {
    activeCount: "{count} active",
    ready: "Ready",
  },
  home: {
    title: "Home",
    urlLabel: "Video URL",
    urlPlaceholder: "Paste a link…",
    paste: "Paste",
    analyze: "Analyze",
    analyzing: "Analyzing…",
    cancelAnalyze: "Cancel",
    reanalyze: "Re-analyze",
    watchClipboard: "Watch clipboard",
    dropHint: "Tip: you can also drag-drop a link here.",
    shortcutsHint: "Shortcuts: Ctrl+V pastes and analyzes · Ctrl+K commands · Ctrl+, opens Settings.",
    invalidUrl: "That link does not look valid.",
    analyzeFailed: "Could not analyze this link. See Logs for details.",
    previewDuration: "Duration",
    unknownDuration: "—",
    kindVideo: "Video",
    kindAudio: "Audio",
    advancedFormats: "Advanced formats",
    useFormat: "Use",
    presetCompatible: "Compatible MP4",
    sizeUnknown: "-",
    entriesSelected: "selected",
    selectAll: "All",
    selectNone: "None",
    queueSelected: "Download selected",
    queueSingle: "Download",
    queuedToast: "Queued {count}.",
    playlistPresetNote: "The preset above applies to every selected entry.",
  },
  batch: {
    title: "Batch",
    description: "Paste many links at once, or drop a .txt file. One link per line.",
    inputLabel: "Links (one per line)",
    inputPlaceholder: "https://…\nhttps://…",
    add: "Add",
    chooseFile: "Choose .txt…",
    analyzeAll: "Analyze all",
    analyzing: "Analyzing…",
    stop: "Stop",
    queueAllReady: "Queue all ready",
    queueing: "Queueing…",
    retryFailed: "Retry failed",
    remove: "Remove",
    expand: "Expand",
    clear: "Clear",
    useGlobalPreset: "Use global preset",
    presetLabel: "Preset",
    empty: "Nothing here yet. Paste links or choose a .txt file.",
    invalidSkipped: "Invalid lines skipped: {n}",
    duplicatesSkipped: "Duplicates skipped: {n}",
    truncatedNote: "Stopped at 500 lines; the rest was ignored.",
    fileTooBig: "That file is over 1 MB.",
    statusPending: "Pending",
    statusAnalyzing: "Analyzing…",
    statusReady: "Ready",
    statusFailed: "Failed",
    queuedToast: "Queued {count}.",
  },
  playlist: {
    downloaded: "Downloaded",
    hideDownloaded: "Hide downloaded",
    filterPlaceholder: "Filter entries…",
    checking: "Checking downloaded…",
  },
  duplicate: {
    title: "Already downloaded?",
    queueMessage: "This link is already in your queue.",
    historyMessage: "You downloaded this before.",
    downloadedOn: "Downloaded:",
    skip: "Skip",
    downloadAnyway: "Download anyway",
    openFile: "Open existing file",
  },
  downloads: {
    title: "Downloads",
    empty: "Nothing here yet. Queue something from Home.",
    pause: "Pause",
    resume: "Resume",
    cancel: "Cancel",
    retry: "Retry",
    retryAll: "Retry all failed",
    retryIn: "Retrying in {n}s · attempt {a}",
    attempt: "Attempt {a}",
    openFile: "Open file",
    showInFolder: "Show in folder",
    showFolder: "Open folder",
    pauseAll: "Pause all",
    resumeAll: "Resume all",
    cancelQueued: "Cancel queued…",
    cancelQueuedConfirm: "Cancel every queued download? They will be kept in history.",
    clearFinished: "Clear finished",
    bulkActions: "Bulk queue actions",
  },
  library: {
    title: "Library",
    searchPlaceholder: "Search title or link…",
    loading: "Loading…",
    empty: "No finished downloads yet.",
    emptySearch: "No matches.",
    redownload: "Download again",
    remove: "Remove",
    clearAll: "Clear all",
    clearConfirm: "Remove all history entries?",
    missing: "Missing",
    locate: "Locate…",
    checking: "Checking files…",
  },
  settings: {
    title: "Settings",
    loading: "Loading…",
    downloadDir: "Download folder",
    browse: "Browse…",
    filenameTemplate: "Filename template",
    filenamePresets: "Presets",
    concurrency: "Simultaneous downloads (1–5)",
    analyzeTimeout: "Analyze timeout (seconds, 10–300)",
    speedLimit: "Speed limit (e.g. 4.2M, empty = unlimited)",
    proxy: "Proxy (empty = direct)",
    cookies: "Cookies from browser (e.g. chrome, empty = off)",
    cookiesFile: "Cookies file (.txt, empty = off)",
    embedThumbnail: "Embed thumbnail",
    embedMetadata: "Embed metadata",
    subtitles: "Download subtitles",
    subtitleLangs: "Subtitle languages",
    embedSubs: "Embed subtitles",
    mergeContainer: "Merge container",
    codecPreference: "Preferred video codec",
    codecAuto: "Auto (site default)",
    codecH264: "H.264 (plays everywhere)",
    codecVp9: "VP9",
    codecAv1: "AV1 (smaller files)",
    thumbnailAccent: "Tint preview with thumbnail colour",
    skipArchived: "Skip playlist videos already in the archive",
    playlistSubfolder: "Download playlists into subfolders",
    clearArchive: "Clear archive…",
    archiveCleared: "Archive cleared.",
    archiveConfirm: "Forget every archived video? Playlists will download them again.",
    sponsorBlock: "Remove SponsorBlock segments",
    theme: "Theme",
    themes: {
      obsidian: "Obsidian",
      midnight: "Midnight",
      ember: "Ember",
    },
    density: "Density",
    densityComfortable: "Comfortable",
    densityCompact: "Compact",
    accent: "Accent colour",
    accentCustom: "Custom hex (#rrggbb)",
    accentReset: "Reset to theme default",
    accentWarning: "Low contrast on accent text — adjusted automatically.",
    postAction: "After download",
    postNone: "Do nothing",
    postOpen: "Open file",
    postReveal: "Show in folder",
    language: "Language",
    languageAuto: "Auto (system)",
    languageEnglish: "English",
    languageMalay: "Bahasa Melayu",
    historyLimit: "Keep history entries (10–5000)",
    autoCheckUpdate: "Check engine updates on launch",
    saved: "Saved.",
    search: "Search settings…",
    clearSearch: "Clear search",
    noMatch: "No settings match.",
    matchCount: "{n} of {t} settings",
  },
  logs: {
    title: "Logs & About",
    engineVersions: "Engine versions",
    appVersion: "App",
    ytdlpVersion: "yt-dlp",
    ffmpegVersion: "ffmpeg",
    checkUpdate: "Check for update",
    updating: "Updating…",
    upToDate: "Engine is up to date.",
    updateFailed: "Update failed. See below.",
    repairEngine: "Repair engine",
    repairing: "Repairing…",
    repaired: "Engine verified.",
    repairFailed: "Repair failed. The app may need reinstalling.",
    viewLog: "View",
    logPlaceholder: "Pick a job to inspect its raw engine log.",
    copyrightNote:
      "You are responsible for respecting copyright and each site's terms. Only download content you own or are allowed to keep.",
  },
  errors: {
    actionRetry: "Retry",
    actionUpdateRetry: "Update engine & retry",
    actionCookiesOnce: "Use once",
    actionCookiesAlways: "Always use",
    actionRepair: "Repair engine",
    actionSettings: "Open settings",
    actionLogs: "Open logs",
    actionFolder: "Choose folder",
    cookiesLabel: "Read cookies from",
    updateBlockedBusy: "Pause or finish the active downloads first, then update.",
    engineUpdated: "Engine updated. Retrying…",
    engineRepairing: "Repairing…",
    engineRepaired: "Engine repaired and verified.",
    engineRepairFailed: "Repair failed. See Logs for details.",
  },
  browsers: {
    chrome: "Google Chrome",
    edge: "Microsoft Edge",
    firefox: "Firefox",
    brave: "Brave",
    chromium: "Chromium",
    opera: "Opera",
    vivaldi: "Vivaldi",
    whale: "Whale",
  },
  menu: {
    label: "Download actions",
    copyUrl: "Copy URL",
    copyPath: "Copy file path",
    retryPreset: "Retry with another preset…",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove from list",
    deleteFile: "Delete file",
    deleteConfirm: "Move this file to the Recycle Bin? The history entry is kept.",
    deletedToast: "Moved to the Recycle Bin.",
    fileDeleted: "File deleted",
    copyFailed: "Copy failed.",
  },
  diagnostics: {
    copy: "Copy diagnostics",
    save: "Save .txt",
    includeUrls: "Include URLs (they may contain private links)",
    preview: "Report preview",
    copied: "Diagnostics copied.",
    saved: "Diagnostics saved.",
    reportTitle: "FluxDL diagnostics",
    reportVersions: "Versions",
    reportSettings: "Settings (redacted)",
    reportErrors: "Recent errors",
    reportNoErrors: "(none)",
    reportLog: "Log tail",
    reportNoLog: "(no log selected)",
  },
  commands: {
    title: "Command palette",
    placeholder: "Type a command…",
    empty: "No matching commands.",
    pasteAnalyze: "Paste clipboard URL and analyze",
    goHome: "Go to Home",
    goDownloads: "Go to Downloads",
    goLibrary: "Go to Library",
    goSettings: "Go to Settings",
    goLogs: "Go to Logs",
    themeObsidian: "Switch to Obsidian theme",
    themeMidnight: "Switch to Midnight theme",
    themeEmber: "Switch to Ember theme",
    updateEngine: "Update yt-dlp engine",
    openDownloadsFolder: "Open downloads folder",
    pauseAll: "Pause all downloads",
    resumeAll: "Resume all downloads",
    retryAll: "Retry all failed downloads",
    clearFinished: "Clear finished downloads",
    toggleDensity: "Toggle comfortable/compact density",
    settingsFolder: "Open Settings: download folder",
    settingsCookies: "Open Settings: cookies",
    settingsProxy: "Open Settings: proxy",
  },
  onboarding: {
    title: "Welcome to FluxDL",
    subtitle: "Three quick steps — you can change everything later in Settings.",
    stepFolder: "Where should downloads go?",
    browse: "Browse…",
    stepTheme: "Pick a theme",
    stepPreset: "Default preset",
    engineOk: "Engine ready",
    engineFail: "Engine check failed — you can still use the app.",
    back: "Back",
    next: "Next",
    done: "Done",
    skip: "Skip",
    replay: "Replay onboarding",
  },
} as const;

export type Strings = typeof EN;

/** Recursive key parity: a missing Bahasa Melayu key fails typecheck. */
export type Parity<T> = { [K in keyof T]: T[K] extends string ? string : Parity<T[K]> };

const MS: Parity<Strings> = {
  appUnavailable: "UI ini mesti berjalan di dalam shell desktop.",
  appUnavailableTitle: "Tidak Tersedia",
  navThemeGroup: "Tema",
  skipToContent: "Langkau ke kandungan",
  toast: {
    region: "Pemberitahuan",
    dismiss: "Tutup",
    finished: "Siap",
    failed: "Gagal",
    removed: "Dipadam daripada sejarah.",
    cleared: "Sejarah dikosongkan.",
  },
  status: {
    activeCount: "{count} aktif",
    ready: "Sedia",
  },
  home: {
    title: "Utama",
    urlLabel: "URL Video",
    urlPlaceholder: "Tampal pautan…",
    paste: "Tampal",
    analyze: "Analisis",
    analyzing: "Menganalisis…",
    cancelAnalyze: "Batal",
    reanalyze: "Analisis semula",
    watchClipboard: "Pantau papan klip",
    dropHint: "Petua: anda juga boleh seret-dan-lepas pautan ke sini.",
    shortcutsHint: "Pintasan: Ctrl+V tampal dan analisis · Ctrl+K perintah · Ctrl+, buka Tetapan.",
    invalidUrl: "Pautan itu tidak sah.",
    analyzeFailed: "Pautan ini tidak dapat dianalisis. Lihat Log.",
    previewDuration: "Tempoh",
    unknownDuration: "—",
    kindVideo: "Video",
    kindAudio: "Audio",
    advancedFormats: "Format lanjutan",
    useFormat: "Guna",
    presetCompatible: "MP4 Serasi",
    sizeUnknown: "-",
    entriesSelected: "dipilih",
    selectAll: "Semua",
    selectNone: "Tiada",
    queueSelected: "Muat turun yang dipilih",
    queueSingle: "Muat turun",
    queuedToast: "Diberatur {count}.",
    playlistPresetNote: "Pratetap di atas terpakai untuk setiap entri yang dipilih.",
  },
  batch: {
    title: "Kelompok",
    description: "Tampal banyak pautan sekali gus, atau lepaskan fail .txt. Satu pautan sebaris.",
    inputLabel: "Pautan (satu sebaris)",
    inputPlaceholder: "https://…\nhttps://…",
    add: "Tambah",
    chooseFile: "Pilih .txt…",
    analyzeAll: "Analisis semua",
    analyzing: "Menganalisis…",
    stop: "Berhenti",
    queueAllReady: "Baris semua yang sedia",
    queueing: "Mebarisi…",
    retryFailed: "Cuba semula yang gagal",
    remove: "Buang",
    expand: "Kembangkan",
    clear: "Padam",
    useGlobalPreset: "Guna pratetap global",
    presetLabel: "Pratetap",
    empty: "Tiada apa-apa lagi. Tampal pautan atau pilih fail .txt.",
    invalidSkipped: "Baris tidak sah dilangkau: {n}",
    duplicatesSkipped: "Duplikat dilangkau: {n}",
    truncatedNote: "Berhenti pada 500 baris; selebihnya diabaikan.",
    fileTooBig: "Fail itu melebihi 1 MB.",
    statusPending: "Menunggu",
    statusAnalyzing: "Menganalisis…",
    statusReady: "Sedia",
    statusFailed: "Gagal",
    queuedToast: "Diberatur {count}.",
  },
  playlist: {
    downloaded: "Dimuat turun",
    hideDownloaded: "Sembunyikan yang dimuat turun",
    filterPlaceholder: "Tapis entri…",
    checking: "Menyemak yang dimuat turun…",
  },
  duplicate: {
    title: "Sudah dimuat turun?",
    queueMessage: "Pautan ini sudah ada dalam baris gilir anda.",
    historyMessage: "Anda pernah memuat turun ini.",
    downloadedOn: "Dimuat turun:",
    skip: "Langkau",
    downloadAnyway: "Muat turun juga",
    openFile: "Buka fail sedia ada",
  },
  downloads: {
    title: "Muat Turun",
    empty: "Tiada apa-apa lagi. Bariskan sesuatu dari Utama.",
    pause: "Jeda",
    resume: "Sambung",
    cancel: "Batal",
    retry: "Cuba semula",
    retryAll: "Cuba semula semua yang gagal",
    retryIn: "Cuba semula dalam {n}s · percubaan {a}",
    attempt: "Percubaan {a}",
    openFile: "Buka fail",
    showInFolder: "Tunjuk dalam folder",
    showFolder: "Buka folder",
    pauseAll: "Jeda semua",
    resumeAll: "Sambung semua",
    cancelQueued: "Batalkan yang berbaris…",
    cancelQueuedConfirm: "Batalkan semua muat turun yang berbaris? Ia akan disimpan dalam sejarah.",
    clearFinished: "Padam yang siap",
    bulkActions: "Tindakan kelompok baris gilir",
  },
  library: {
    title: "Pustaka",
    searchPlaceholder: "Cari tajuk atau pautan…",
    loading: "Memuatkan…",
    empty: "Tiada muat turun siap lagi.",
    emptySearch: "Tiada padanan.",
    redownload: "Muat turun semula",
    remove: "Buang",
    clearAll: "Padam semua",
    clearConfirm: "Buang semua entri sejarah?",
    missing: "Fail tiada",
    locate: "Cari…",
    checking: "Menyemak fail…",
  },
  settings: {
    title: "Tetapan",
    loading: "Memuatkan…",
    downloadDir: "Folder muat turun",
    browse: "Layari…",
    filenameTemplate: "Templat nama fail",
    filenamePresets: "Pratetap",
    concurrency: "Muat turun serentak (1–5)",
    analyzeTimeout: "Masa tamat analisis (saat, 10–300)",
    speedLimit: "Had laju (cth. 4.2M, kosong = tanpa had)",
    proxy: "Proksi (kosong = terus)",
    cookies: "Kuki dari pelayar (cth. chrome, kosong = mati)",
    cookiesFile: "Fail kuki (.txt, kosong = mati)",
    embedThumbnail: "Benamkan gambar kecil",
    embedMetadata: "Benamkan metadata",
    subtitles: "Muat turun sari kata",
    subtitleLangs: "Bahasa sari kata",
    embedSubs: "Benamkan sari kata",
    mergeContainer: "Bekas cantuman",
    codecPreference: "Codec video pilihan",
    codecAuto: "Auto (lalai tapak)",
    codecH264: "H.264 (boleh main di mana-mana)",
    codecVp9: "VP9",
    codecAv1: "AV1 (fail lebih kecil)",
    thumbnailAccent: "Warnakan pratonton ikut gambar kecil",
    skipArchived: "Langkau video senarai yang sudah diarkib",
    playlistSubfolder: "Muat turun senarai ke dalam subfolder",
    clearArchive: "Padam arkib…",
    archiveCleared: "Arkib dipadamkan.",
    archiveConfirm: "Lupakan semua video yang diarkib? Senarai akan memuat turunnya semula.",
    sponsorBlock: "Buang segmen SponsorBlock",
    theme: "Tema",
    themes: {
      obsidian: "Obsidian",
      midnight: "Midnight",
      ember: "Ember",
    },
    density: "Kepadatan",
    densityComfortable: "Selesa",
    densityCompact: "Padat",
    accent: "Warna aksen",
    accentCustom: "Heks tersuai (#rrggbb)",
    accentReset: "Kembali ke lalai tema",
    accentWarning: "Kontras rendah pada teks aksen — diselaraskan automatik.",
    postAction: "Selepas muat turun",
    postNone: "Jangan buat apa-apa",
    postOpen: "Buka fail",
    postReveal: "Tunjuk dalam folder",
    language: "Bahasa",
    languageAuto: "Auto (sistem)",
    languageEnglish: "English",
    languageMalay: "Bahasa Melayu",
    historyLimit: "Simpan entri sejarah (10–5000)",
    autoCheckUpdate: "Semak kemas kini enjin semasa mula",
    saved: "Disimpan.",
    search: "Cari tetapan…",
    clearSearch: "Padam carian",
    noMatch: "Tiada tetapan sepadan.",
    matchCount: "{n} daripada {t} tetapan",
  },
  logs: {
    title: "Log & Perihal",
    engineVersions: "Versi enjin",
    appVersion: "App",
    ytdlpVersion: "yt-dlp",
    ffmpegVersion: "ffmpeg",
    checkUpdate: "Semak kemas kini",
    updating: "Mengemas kini…",
    upToDate: "Enjin sudah terkini.",
    updateFailed: "Kemas kini gagal. Lihat di bawah.",
    repairEngine: "Baiki enjin",
    repairing: "Membaiki…",
    repaired: "Enjin disahkan.",
    repairFailed: "Pembaikan gagal. App mungkin perlu dipasang semula.",
    viewLog: "Lihat",
    logPlaceholder: "Pilih kerja untuk melihat log enjin mentahnya.",
    copyrightNote:
      "Anda bertanggungjawab menghormati hak cipta dan syarat setiap tapak. Muat turun hanya kandungan milik anda atau yang dibenarkan.",
  },
  errors: {
    actionRetry: "Cuba semula",
    actionUpdateRetry: "Kemas kini enjin & cuba semula",
    actionCookiesOnce: "Guna sekali",
    actionCookiesAlways: "Sentiasa guna",
    actionRepair: "Baiki enjin",
    actionSettings: "Buka tetapan",
    actionLogs: "Buka log",
    actionFolder: "Pilih folder",
    cookiesLabel: "Baca kuki dari",
    updateBlockedBusy: "Jeda atau habiskan muat turun aktif dahulu, kemudian kemas kini.",
    engineUpdated: "Enjin dikemas kini. Mencuba semula…",
    engineRepairing: "Membaiki…",
    engineRepaired: "Enjin dibaiki dan disahkan.",
    engineRepairFailed: "Pembaikan gagal. Lihat Log.",
  },
  browsers: {
    chrome: "Google Chrome",
    edge: "Microsoft Edge",
    firefox: "Firefox",
    brave: "Brave",
    chromium: "Chromium",
    opera: "Opera",
    vivaldi: "Vivaldi",
    whale: "Whale",
  },
  menu: {
    label: "Tindakan muat turun",
    copyUrl: "Salin URL",
    copyPath: "Salin path fail",
    retryPreset: "Cuba semula dengan pratetap lain…",
    moveUp: "Gerak ke atas",
    moveDown: "Gerak ke bawah",
    remove: "Buang dari senarai",
    deleteFile: "Padam fail",
    deleteConfirm: "Alihkan fail ini ke Recycle Bin? Entri sejarah dikekalkan.",
    deletedToast: "Dialih ke Recycle Bin.",
    fileDeleted: "Fail dipadamkan",
    copyFailed: "Salinan gagal.",
  },
  diagnostics: {
    copy: "Salin diagnostik",
    save: "Simpan .txt",
    includeUrls: "Sertakan URL (mungkin mengandungi pautan peribadi)",
    preview: "Pratonton laporan",
    copied: "Diagnostik disalin.",
    saved: "Diagnostik disimpan.",
    reportTitle: "Diagnostik FluxDL",
    reportVersions: "Versi",
    reportSettings: "Tetapan (diredaksi)",
    reportErrors: "Ralat terkini",
    reportNoErrors: "(tiada)",
    reportLog: "Ekor log",
    reportNoLog: "(tiada log dipilih)",
  },
  commands: {
    title: "Palet perintah",
    placeholder: "Taip perintah…",
    empty: "Tiada perintah sepadan.",
    pasteAnalyze: "Tampal URL papan klip dan analisis",
    goHome: "Pergi ke Utama",
    goDownloads: "Pergi ke Muat Turun",
    goLibrary: "Pergi ke Pustaka",
    goSettings: "Pergi ke Tetapan",
    goLogs: "Pergi ke Log",
    themeObsidian: "Tukar ke tema Obsidian",
    themeMidnight: "Tukar ke tema Midnight",
    themeEmber: "Tukar ke tema Ember",
    updateEngine: "Kemas kini enjin yt-dlp",
    openDownloadsFolder: "Buka folder muat turun",
    pauseAll: "Jeda semua muat turun",
    resumeAll: "Sambung semua muat turun",
    retryAll: "Cuba semula semua muat turun yang gagal",
    clearFinished: "Padam muat turun yang siap",
    toggleDensity: "Tukar ketumpatan selesa/padat",
    settingsFolder: "Buka Tetapan: folder muat turun",
    settingsCookies: "Buka Tetapan: kuki",
    settingsProxy: "Buka Tetapan: proksi",
  },
  onboarding: {
    title: "Selamat datang ke FluxDL",
    subtitle: "Tiga langkah pantas — anda boleh ubah semuanya kemudian dalam Tetapan.",
    stepFolder: "Muat turun patut pergi ke mana?",
    browse: "Layari…",
    stepTheme: "Pilih tema",
    stepPreset: "Pratetap lalai",
    engineOk: "Enjin sedia",
    engineFail: "Semakan enjin gagal — anda masih boleh guna app.",
    back: "Kembali",
    next: "Seterusnya",
    done: "Siap",
    skip: "Langkau",
    replay: "Ulangi onboarding",
  },
};

/** Default (English) dictionary — existing STRINGS imports keep working. */
export const STRINGS: Strings = EN;

/** Bahasa Melayu dictionary (key parity enforced by Parity<Strings>). */
export const STRINGS_MS: Parity<Strings> = MS;
